### ISSUE TITLE
Can't get multiple tag values to work

### ISSUE THREAD

**Issue by MrMMorris** [chef/knife-ec2#220]
see https://github.com/forward3d/cap-ec2/issues/24

**Comment by btm** [comment]
If anyone has an issue I wonder if `--tags 'tag1=val1,tag2=val2'` works (single quotes). It'd be good to add support for specifying `--tags` multiple times, as we find that's the easiest way to avoid issues passing lists on the command line.

**Comment by dheerajd-msys** [comment]
@MrMMorris, You can provide multiple values semicolon separated. I verified that giving multiple values comma separated does produce error. However providing values as `--tags 'tag1=val1;val2'` works fine.

**Comment by NimishaS** [comment]
@MrMMorris , I hope your issue is resolved by the solution provided by @dheerajd-msys. 

Please feel free to re-open if you still face problem.
