### ISSUE TITLE
Allow instances to be provisioned with source/dest checks disabled

### ISSUE THREAD

**Issue by brettcave** [chef/knife-ec2#225]
Given I am using knife to provision an instance that I would like to have source / destination checks disabled on (e.g. for a router / gateway),
When I provision the instance using `knife ec2 server create`
Then a flag is available to toggle instance attributes.

Looking at the RunInstance API, it is not possible to provide attributes at this point. However, knife-ec2 doesn't provide a mechanism to modify attributes of existing instances.

In order to achieve this, A) make the launch instance call and wait until the instance attributes can be modified before bootstrapping knife, or B) add a new module to knife ec2 that allows managing instances, e.g. by using the ModifyInstanceAttribute end-point (SourceDestCheck parameter). 

Option B would be a nice extension to ec2 for managing instances, and would also allow other modifications, such as changing user data, disabling API termination, security groups.

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-ModifyInstanceAttribute.html
http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ApiReference-query-RunInstances.html

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_NAT_Instance.html#EIP_Disable_SrcDestCheck

Each EC2 instance performs source/destination checks by default. This means that the instance must be the source or destination of any traffic it sends or receives. However, a NAT instance must be able to send and receive traffic when the source or destination is not itself. Therefore, you must disable source/destination checks on the NAT instance.

**Comment by chrisduong** [comment]
+1

**Comment by dheerajd-msys** [comment]
Thanks @brettcave for pointing this out. We will look into this.

**Comment by breisig** [comment]
This would be a GREAT feature to have.

**Comment by breisig** [comment]
Wow, still no updates?
