### ISSUE TITLE
change -j to match chef-client

### ISSUE THREAD

**Issue by MrMMorris** [chef/knife-ec2#226]
currently -j in chef-client can be used to specify a json FILE whereas -j in knife ec2 only takes a json STRING as an input. 

It would be nice for knife ec2 to match chef-client and accept a json file :)

**Comment by NAshwini** [comment]
Hi @MrMMorris ,
This feature is been added from  Chef Client 12.6 mentioned the same in knife bootstrap doc: https://docs.chef.io/knife_bootstrap.html and merge in PR: https://github.com/chef/knife-ec2/pull/400.
Hence closing this issue.
