### ISSUE TITLE
Tag node in Chef

### ISSUE THREAD

**Issue by galindro** [chef/knife-ec2#234]
As posted here: http://stackoverflow.com/questions/6078294/how-can-i-tag-an-ec2-instance-using-ruby-in-chef#comment19103559_11485434, it seems that knife ec2 doesn't tag the node in chef context, only in aws context. So, it would be nice if knife ec2 could tag the node in chef context too...

**Comment by perplexes** [comment]
@juliandunn the tags do not appear in ohai's metadata because they don't appear in the ec2 metadata service.

I wrote a script that will copy all non-Name AWS tags to chef: https://gist.github.com/perplexes/50f82116b9f5fafaeb45

**Comment by dheerajd-msys** [comment]
@galindro Thanks for pointing this out. Although `knife ec2 server create` have an option `--hint` which  takes input in json file and copies the data in target node at `/etc/chef/ohai/hints/<HINT_NAME.jason>`.
Please let me know if that serves your purpose. 
Command for your reference : 
`knife ec2 server create --flavor 't2.micro' -x <USER> -P 'PASSWORD' --ssh-key 'xxxx' --image 'ami-b63769a1' -N <NODE-NAME> --hint HINT-NAME=/path/to/file.json`

knife-ec2 v0.13.0

**Comment by NimishaS** [comment]
Fixed in https://github.com/chef/knife-ec2/pull/476

**Comment by popsikle** [comment]
Ugh, is there a way to only tag the nodes in ec2 now?  This is a terrible change.  All of my new nodes are now tagged with my ec2 tags as well, which are not the same as my chef tags, they dont even have the same format.  

ec2-tags are KEY=VALUE, so now all my nodes look like this:
Tags:        Application=xxxx, Environment=yyyy, Service=xxx, redis_xxxxx_slave

**Comment by NimishaS** [comment]
@popsikle , https://github.com/chef/knife-ec2/pull/492 should fix your issue.
