### ISSUE TITLE
template_file option not clear

### ISSUE THREAD

**Issue by erez-rabih** [chef/knife-ec2#235]
Hi,

I wanted to point two things regarding the template_file option on server create command:

1. It isn't really clear a template for what? for client.rb?
2. If I am not missing anything here, this options is not really used throughout the code on this project. Am I right? If yes, maybe it should be omitted.

**Comment by kaustubh-d** [comment]
@erez-rabih @tarrall 

`--template-file` used during node bootstrap and knife-ec2 sends this option to chef bootstrap process.
