### ISSUE TITLE
Tilde in path name for config parameters does not work

### ISSUE THREAD

**Issue by fletchowns** [chef/knife-ec2#245]
I added the following to my knife.rb:

```
knife[:secret_file] = '~/.chef/encrypted_data_bag_secret'
```

Then I did a `knife ec2 server create` which resulted in the following error message:

> No secret specified to load_secret and no secret found at /etc/chef/encrypted_data_bag_secret

I was able to get it working by providing it on the command line:

```
knife ec2 server create --secret-file ~/.chef/encrypted_data_bag_secret
```

Not sure if this is a knife bug or knife-ec2 bug, so hopefully I'm in the right spot.

**Comment by stark525** [comment]
Related issue, I was trying to `knife ec2 create` and pass in `--identity-file ~/.ssh/MYID.pem` with a bunch of other parameters.  SSH using the key would fail and it would prompt me for a password. 

I was able to resolve the bug by putting identity-file as my first flag, e.g. `knife ec2 create --identity-file ~/.ssh/MYID.pem --ssh-user ec2-user -I 'ami-xxxxxx' ...`  

I did not have to set an absolute path.

**Comment by dheerajd-msys** [comment]
I do not get any error while providing `--identity-file` in command line or in my knife.rb as `knife[:identity_file] = "~/Downloads/my-pem.pem"`. I used Powershell to launch the `knife ec2 server create`
 ,`ChefDK 0.19.6` and latest `knife-ec2 0.13.0`

**Comment by dheerajd-msys** [comment]
Closing this issue as per above comments. Please feel free to re-open if error persists.
Thanks.
