### ISSUE TITLE
Creating instances in the Frankfurt zone

### ISSUE THREAD

**Issue by MrPink** [chef/knife-ec2#256]
Hi,

I'm trying to use the new eu-central-1 region but  getting issues doing anything with eu-central-1, for example

iBrain:~ will$ knife ec2 server list -V --region eu-central-1
ERROR: Fog::Compute::AWS::Error: AuthFailure => AWS was not able to validate the provided access credentials

However 

iBrain:~ will$ knife ec2 server list -V --region eu-west-1

works without issue, is there something I'm missing?

Thanks,
Will

**Comment by evtuhovich** [comment]
@kwilczynski, Fog folks merge and release this feature in 1.25.0, please update dependency

**Comment by siddheshwar-more** [comment]
@evtuhovich -

We did changes related to fog version in **knife-ec2** master branch, but its not yet released.

You can try this -
```
git clone https://github.com/opscode/knife-ec2
cd knife-ec2
gem build knife-ec2.gemspec
gem install knife-ec2-0.10.0.rc.1.gem
```

**Comment by sfroehler** [comment]
Still no release with fog 1.25.0 support? How can we help to get this released?

**Comment by siddheshwar-more** [comment]
@sfroehler 

We are working on knife-ec2 release, this is going to be out very soon!

**Comment by sfroehler** [comment]
@siddheshwar-more that is good news. Thanks a lot! :+1:

**Comment by rcsavage** [comment]
What about if you have multiple AWS Accounts and using AWS Switch Role?   Does this support Switch Role and Security Tokens?
