### ISSUE TITLE
Spot-Instance Support ?

### ISSUE THREAD

**Issue by ekle** [chef/knife-ec2#257]
referring to https://tickets.opscode.com/browse/KNIFE-177
> Seth Vargo added a comment - 11/Jul/13 7:53 PM
> We are currently doing a refactor of various knife plugins that would allow this capability without this particular change. We will track this on an internal ticket and try to include this functionality in an upcoming refactor.

What is the current status of this ?
spot instances would be a really nice feature.

**Comment by alexpop** [comment]
+1

**Comment by kaustubh-d** [comment]
Spot instance related changes are merged in master
