### ISSUE TITLE
Changes based on Chef 12 bootstrap command line options

### ISSUE THREAD

**Issue by sersut** [chef/knife-ec2#258]
In Chef Client 12 some of the bootstrap options have changed / cleaned up. More information can be found here: 

https://github.com/opscode/chef/blob/master/RELEASE_NOTES.md#boostrap-changes

In order to match these at a minimum: 
- Remove `template-file`, `distro` options and add `bootstrap-template` option.
- Set the default bootstrap template if we need to change it by overriding `default_bootstrap_template` method.
- Add `:ssl_verify_mode` & `:verify_api_cert` options.

We're making sure that Chef Client 12.0.0 works with the latest versions of knife cloud plugins. This change is primarily required to reduce the potential confusion. 

@adamedx can we have matching issues for other knife cloud plugins as well?

**Comment by jaconstantine** [comment]
I'd also like to see all the options of ```knife bootstrap``` supported with ```knife ec2 create```. Some non-supported examples are:
  --server-url 
  --bootstrap-url

**Comment by gbish** [comment]
Hey,
Have you seen this before? That's something really nice, more info here <http://tholyheto.wordpressquickstart.net/oijuto>

Faithfully, hebgb@blueyonder.co.uk

**Comment by dheerajd-msys** [comment]
@sersut Options `template-file` and `distro` are deprecated and `bootstrap-template` is added. Also `:ssl_verify_mode` & `:verify_api_cert` options are added. 

@jaconstantine `--server-url` & `--bootstrap-url` options are supported in latest `knife-ec2`.
Closing the issue, feel free to re-open if there are any issues with it.
