### ISSUE TITLE
Knife ec2 server create returns good even when the remote chef run fails

### ISSUE THREAD

**Issue by pbecotte** [chef/knife-ec2#269]
When bootstrapping a server, especially from an automated process, I would like to get notified if anything goes wrong.  However, knife ec2 server create always returns a good status.  I will have to add error checking to my launch scripts, but it kind of surprised me that it didn't handle this on its own.

**Comment by NimishaS** [comment]
@pbecotte , please provide us following details:
1. Are you giving any cookbook in runlist while creating ec2 instance?
2. If so, does that cookbook raise error while `knife ec2 server create` executes successfully?
3. Are you using released `knife-ec2` version?
4. Do you want to report bootstrap success/failure status to your launch script? In that case `chef-handler` can be useful.
https://docs.chef.io/handlers.html

In case you are not trying what we mentioned above, please share your command and logs returned with -VV option.

**Comment by NimishaS** [comment]
Hello @pbecotte , please share the details of this issue in case you are still facing it.
Can we close this issue otherwise?

**Comment by pbecotte** [comment]
Sorry for the delay!  I am running knife ec2 server create from a bash script.  I dump the output into a temp file so that I can get the IP address and name of the server for further operations.  Every once in a while, one of the cookbooks would fail for whatever reason- like I didn't upload all of the cookbooks to the server or something stupid like that.  However, the bash script with -e set still completed sucessfully.

knife ec2 server create -S aws -i ~/.ssh/Bamx-Dev.pem -x ubuntu -E ${ENV} -I ${BASE_AMI} -f t2.medium -r "role[application]" --bootstrap-version "11.6" | tee ${TEMP_FILE}

I worked around the issue by searching the temp file for "Chef Client finished" and exiting directly if it isn't found, which solves my need.  However, it seems like knife ec2 server create should return 1 if the remote client fails (if that's even possible, I suppose!)

if grep 'Chef Client finished' ${TEMP_FILE}; then
 echo "Chef Client Finished"
else
 echo "Chef didn't finish"
 exit 1
fi

**Comment by NimishaS** [comment]
Hello @pbecotte , I tried the bash script written below and it returned the correct exit code(i.e. 1) since the cookbook provided with -r option is not uploaded.
```shell
#!/bin/sh

set -e
export PATH=$PATH:/opt/chef/bin:/opt/chef/embedded/bin

knife ec2 server create -N nim-test -I ami-71136618 --ssh-user root --bootstrap-protocol ssh --identity-file sidec2key.pem -r "recipe[testr]"
echo "*******************************************************"
```

`knife ec2 server create` command is returning exit code status 1 in case bootstrap fails for any reason. Are you setting `set -e` at the top of the script as shown in the code above?

**Comment by NimishaS** [comment]
Hi @pbecotte , is your issue resolved?

**Comment by pbecotte** [comment]
So... Sorry?  Turns out I am not that good at bash scripting... The pipe
was swallowing the error code.  You can feel free to resolve this with my
apologies!

**Comment by NimishaS** [comment]
Thanks @pbecotte

**Comment by gbish** [comment]
Hello,

I've recently found one curious case about the stuff we discussed last time, just take a look <http://gojoquohy.sterlingtonroadstorage.com/oifgus>

Be well, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hello,

Here is some information that inspired me a lot, read it please, it may be helpful <http://hycroheju.astropuncture.org/oikufjav>

Typos courtesy of my iPhone, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hi,

Here is a bit of news about our friends' wedding, just take a look here <http://joshoginti.mikedispenzaonline.com/oibwu>

Speak to you later, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hi,

Have you heard the latest gossip? This is what you have to read <http://pephifrepru.networktask.com/oihlszez>

Hope this helps, hebgb@blueyonder.co.uk
