### ISSUE TITLE
Error when AWS config path specified

### ISSUE THREAD

**Issue by larryebaum** [chef/knife-ec2#271]
chef: 11.18.0.rc.1   -- awscli 1.6.5

Attempted multiple variations of the below knife.rb setting (also with single quotes)
`knife[:aws_credential_file] = "~/.aws/config"`
`knife[:aws_credential_file] = "~/.aws/credentials"`

All return error on execution `knife ec2 server list`
`ERROR: Errno::ENOENT: No such file or directory @ rb_sysopen - ~/.aws/config`

Setting an environment variable for the awscli config file and using this in knife.rb works.
`knife[:aws_credential_file] = ENV['AWS_CONFIG_FILE']`

**Comment by stephenlauck** [comment]
Larry take a look around here https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_base.rb#L103

and you could probably just make ~/.aws/config the default and add a flag for the AWS credentials ie --aws-config ~/dev/foo/.aws/config.

**Comment by kaustubh-d** [comment]
@larryebaum @stephenlauck

Here, please use  `knife[:aws_credential_file]= <full_path>` instead of  `knife[:aws_credential_file]= ~/.aws/config`.

EX-
`knife[:aws_credential_file]= '/home/ubuntu/.aws/config'`
