### ISSUE TITLE
knife-ec2 0.10.0 references fog-1.23.0, fog-1.23.0 references an incomplete list of aws regions so requests fail with unknown region response

### ISSUE THREAD

**Issue by andyglick** [chef/knife-ec2#274]
the knife-ec2 knife plugin has a dependency on fog, the latest knife-ec2 version 0.10.0 has a hard coded dependency to fog 1.23.0. fog-1.23.0 references logic that has an incomplete list of aws regions and does not include any AWS gov-cloud regions. so correctly submitted knife-ec2 requests fail when using knife-ec2 0.10.0 with an "unknown region" error 

fog 1.27.0 references the fog-aws gem which contains logic that references all of the AWS region codes

could knife-ec2's fog dependency be bumped to 1.27.0?

**Comment by siddheshwar-more** [comment]
@andyglick 
For region related issue - https://github.com/chef/knife-ec2/issues/260 .
We recently updated fog to 1.25.0 in **knife-ec2 master** branch. Can you try with master branch?
Steps- 
1. $ git clone https://github.com/chef/knife-ec2
3. $ gem uninstall knife-ec2
4. $ gem build knife-ec2.gemspec
5. $ gem install knife-ec2-0.10.0.rc.1.gem

`$ knife ec2 <your_command> --region <gov-cloud-region>`

Let us know result.
Thank you!

**Comment by andyglick** [comment]
when I followed your instructions using chef version 11.18.6  the region us-gov-west-1 does resolve as expected. This issue can be closed

**Comment by siddheshwar-more** [comment]
Cool!

**Comment by gbish** [comment]
Hello,

Just take a look at that amazing and wonderful stuff, you're going to love it for sure!  More info here <http://stibicena.deepenyourpractice.com/oisnd>

hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hey,

I found some old photos of us, these are really precious memories for me, just take a look <http://nyhucymo.qponomics.net/oivik>

Yours faithfully, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hello,

I just wanted to share some interesting thoughts about amazing people I met yesterday, please read more here <http://nkothusaphe.kylenowlinphotography.com/oikaiglw>

Yours faithfully, hebgb@blueyonder.co.uk
