### ISSUE TITLE
KNIFE-464 merge was reverted

### ISSUE THREAD

**Issue by chuckg** [chef/knife-ec2#276]
The patch for KNIFE-464 was reverted with the following merge: 1e666b5. The original merge happened in f62f79a, the original pull request can be viewed in #211. Was it reverted due to some confusion over the contributor licenses? Please see the notes in the pull request, we'd love to see this issue resolved and merged into the knife-ec2 tool.

Original ticket:
https://tickets.opscode.com/browse/KNIFE-464 

New PR:
https://github.com/chef/knife-ec2/pull/289

**Comment by NimishaS** [comment]
@chuckg , STS token related changes have been merged again in this PR: https://github.com/chef/knife-ec2/pull/332. Earlier it was reverted due to license issue. Thank you for your contribution.
