### ISSUE TITLE
support ssh to internal ip

### ISSUE THREAD

**Issue by blueharford** [chef/knife-ec2#278]
make a flag to make the knife ec2 command use the internal IP when launching and bootstrapping a server

**Comment by kaustubh-d** [comment]
@blueharford 
You can use `--server-connect-attribute private_ip_address` option to use private ip during bootstrapping and '--private-ip-address 10.0.0.12' option to specify private ip in VPC mode.

@jamescott Could you please verify- is there any docs available for these options.
