### ISSUE TITLE
Is fog ~> 1.25.0 really necessary?

### ISSUE THREAD

**Issue by L2G** [chef/knife-ec2#281]
The Fog version dependency of `~> 1.25.0` guarantees that any other Ruby gem with a dependency on Fog 1.26 or newer will be incompatible with this one (at least if both are being managed by Bundler). I don't think this is what you want.

**Comment by andyglick** [comment]
yes, couldn't you change the dependency specification from (~> 1.25.0) to (>= 1.25.0) that way I could reference 1.27.0 in my project and the knife-ec2 gem could still work for me

**Comment by ProTip** [comment]
This breaks it with the current chefdk which has fog 1.3.0 .

**Comment by shortdudey123** [comment]
+1 on removing this specific version pinning

**Comment by Dee-2015** [comment]
Hi, 

On Windows this still happens:

 chef gem install knife-ec2
ERROR:  Error installing knife-ec2:
        invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodE
ror) in C:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/cache/fog-1.23.0.gem

I had to uninstall the 1.3x.0 version and manually install the 1.23 version.

**Comment by tas50** [comment]
The latest knife-ec2 (0.11) fixes the chefdk incompatibility

**Comment by tas50** [comment]
Closing this out since the latest release quiets the errors and master now using fog-aws, which avoids hard pins on the fog gem itself.
