### ISSUE TITLE
A noisy fog error 

### ISSUE THREAD

**Issue by okram999** [chef/knife-ec2#286]
This is just annoying but dont seem to beak anything yet.. 

→ knife ec2 server list
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/rackspace/mock_data.rb:42: warning: duplicated key at line 80 ignored: "name"
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/dhcp_options.rb:54: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/addresses.rb:55: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/images.rb:45: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/internet_gateways.rb:54: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/key_pairs.rb:50: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/network_acls.rb:82: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/network_interfaces.rb:87: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/route_tables.rb:55: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/security_groups.rb:58: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/snapshots.rb:18: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/tags.rb:17: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/volumes.rb:63: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/subnets.rb:58: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/models/compute/vpcs.rb:56: warning: circular argument reference - filters
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0/lib/fog/aws/requests/compute/describe_network_acls.rb:70: warning: duplicated key at line 74 ignored: "egress"

Can't update the gem 'fog' to the latest & greatest, looks like knife-ec2 have locked it down

○ → bundle update fog
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "fog":
  In Gemfile:
    knife-ec2 (>= 0) ruby depends on
      fog (~> 1.23.0) ruby

I see this PR: https://github.com/chef/knife-ec2/pull/268  , does this mean knife-ec2 should be able to bump up the fog gem versions?

Some info: 
|ruby-2.2.1@aws_test| work-virtual-machine in ~/workspace/aws_test
○ → bundle show knife-ec2
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/knife-ec2-0.10.0

|ruby-2.2.1@aws_test| work-virtual-machine in ~/workspace/aws_test
○ → bundle show fog
/home/work/.rvm/gems/ruby-2.2.1@aws_test/gems/fog-1.23.0

**Comment by tas50** [comment]
This is fixed in a later version of Fog, but this project pins to an old release.  If the deps in the gemspec here are bumped this will go away for us Ruby 2.2 users.

**Comment by shortdudey123** [comment]
Related to https://github.com/chef/knife-ec2/issues/281

**Comment by gbish** [comment]
Hi,

I've started a new project recently, so you can find some examples of my recenr works here <http://tharyguta.infinityemarket.com/oicle>

Hope this helps, hebgb@blueyonder.co.uk
