### ISSUE TITLE
Doc pages both point to each other.

### ISSUE THREAD

**Issue by jorhett** [chef/knife-ec2#291]
This says documentation is at 

    Documentation: http://docs.opscode.com/plugin_knife_ec2.html

When you go to that page, it is empty and says documentation can be found here.

**Comment by gyoza** [comment]
Yea this really sucks, trying to look something up, can this please be fixed?

**Comment by NimishaS** [comment]
@jorhett , @gyoza : this will be taken care of here https://github.com/chef/knife-ec2/pull/296. Thanks for pointing it out!

**Comment by signe** [comment]
I was about to point out the infinite redirection loop... nice to know someone saw it first.  :stuck_out_tongue_winking_eye:
