### ISSUE TITLE
Ability to use EC2 data in Chef settings

### ISSUE THREAD

**Issue by jorhett** [chef/knife-ec2#292]
I keep thinking this should be possible but I can't find any docs or code which shows this. As the EC2 node is created and the instance data is returned before the bootstrap operation starts, it would be useful to be able to use instance data in the Chef bootstrap variables.

The single most obvious example would be:

```
--node-name "nodetype-#{server.id}"
```

**Comment by dheerajd-msys** [comment]
Thank you @jorhett  for pointing this out. We will work on this.

**Comment by NimishaS** [comment]
@jorhett , are you suggesting that it should be possible to pass `--node-name "nodetype-#{server.id}"` in the `knife ec2 server create` command from CLI?
OR do you want `knife-ec2` to set default node-name as `nodetype-#{server.id}` itself?

**Comment by jorhett** [comment]
Nothing automatic. It was mostly just a thought that by the time `knife` is called, we have all the data from the ec2 instance creation available to us. So your first example is closer to what I was thinking, albeit I don't care about exact formatting.

At every place I've worked we've had to replace/wrap knife ourselves to make use of that data, and a simple change here would obviate that requirement for each customer.

**Comment by NimishaS** [comment]
@jorhett , the first approach of passing `--node-name "nodetype-#{server.id}"` from the CLI is not possible because at the time of running  `knife ec2 server create` command, `server` object is not available as the server gets created later. Infact none of the objects are available at that time. Only static data can be passed.

Can you please help us in understanding the use-case so that we can suggest an alternative approach?

**Comment by jorhett** [comment]
As I said, what the variables are named etc doesn't matter. Please don't consider the exact example provided and consider the use.

The use case is simple and has been repeated three times now: allow knife to make use of variables containing data provided by the EC2 instance creation. Every company I've worked for ends up writing wrapper programs instead of using knife so that results from the image creation can be used by knife. Order of operations is to create the EC2 node, wait for it to boot, and then use `knife` to login and set it up. If you delay the interpolation of variables used by knife until after the results from the EC2 node creation comes back, it provides significant value to the user and avoids the need for them to write their own code to work around this problem.

**Comment by btm** [comment]
The functionality would probably be best implemented like `lazy` in the chef-client: https://docs.chef.io/resource_common.html#lazy-evaluation

**Comment by NimishaS** [comment]
@jorhett ,  this issue is resolved in `knife-ec2 0.15.0`.
Please refer https://github.com/chef/knife-ec2#adding-server_id-to-the-node-name to understand the usage.
