### ISSUE TITLE
'server delete' doesn't display Name in confirmation

### ISSUE THREAD

**Issue by signe** [chef/knife-ec2#308]
Without displaying the instance name in the confirmation, the list feels incomplete.  

All other bits aside, the name is immediately recognizable and doesn't require comparing alphanumeric IDs or IP addresses to make sure you're terminating the correct machine.

```
$ knife ec2 server delete i-0d03d9e4 -P -N chef-client
Instance ID: i-0d03d9e4
Flavor: t2.small
Image: ami-d05e75b8
Region: us-east-1
Availability Zone: us-east-1a
Security Groups: default
SSH Key: [...]
Root Device Type: ebs
Public IP Address: 52.1.123.244
Private DNS Name: ip-172-30-0-161.ec2.internal
Private IP Address: 172.30.0.161

Do you really want to delete this server? (Y/N)
```

**Comment by Vasu1105** [comment]
Fixed in https://github.com/chef/knife-ec2/pull/312/files and merged in master.
