### ISSUE TITLE
Automatically pass ec2 hint during bootstrap

### ISSUE THREAD

**Issue by signe** [chef/knife-ec2#309]
Create /etc/chef/ohai/hints/ec2.json prior to installing/executing chef-client to ensure that ohai builds the ec2 metadata

Since I'm launching inside a VPC, ohai doesn't seem to recognize the instances as ec2 for whatever reason.  Since this is the 'ec2' plugin, it makes complete sense to add this hinting automatically.

**Comment by siddheshwar-more** [comment]
@signe We are looking into this..

**Comment by signe** [comment]
For now, I accomplished it by using this at the top of my default recipe

```
ohai_hint 'ec2' do
	content {}
end
include_recipe 'ohai'
```

`knife bootstrap` accomplishes this with the --hint flag, passing in a hint name, and a file containing the json.  The ec2 hint can be empty, it just needs to be present.

**Comment by cmoad** [comment]
I am also looking for a way to enable the iam hint during the "knife ec2 create" process.

**Comment by btm** [comment]
This has been happening automatically for three years. There's been a couple tweaks, but support was added here: 4a6a8175795a53fda3bb1143d58b113b92832d69. I just created an instance in vpc with up to date software and verified that `/etc/chef/ohai/hints/ec2.json` was present. The knife-ec2 plugin defaults to adding this hint, and it is passed to the default bootstrap template (chef-full) that comes with chef, which creates the hints files before chef-client is run. Perhaps you were using a custom bootstrap template?

**Comment by signe** [comment]
No - this was reported with a stock configuration, installed using the knife-ec2 gem, and the machines were installing chef via omnibus.  I have not been re-testing since shortly after creating the issue because I was only using it for bootstrapping test machines while designing my base cookbook.  I can give it another try, but it was definitely not happening on its own.

**Comment by btm** [comment]
Cool. If you get a repro case, I'm sure I can fix it pretty quickly. Lemme know.

**Comment by btm** [comment]
@signe I'm going to close this issue, I presume you've moved on and nobody else has reported this in almost a year. If anyone has an issue with the hints file please comment as much.
