### ISSUE TITLE
knife ec2 does not conform to AWS/EC2 switch role (security tokens)

### ISSUE THREAD

**Issue by rcsavage** [chef/knife-ec2#311]
Evidently, the knife ec2 plugin only works with AWS access keys and secret access keys tied to account specific users.   It does not confirm to AWS "switch" role temporary access/secret keys based on SECURITY TOKENS.   We need the ec2 plugin to conform to this as temporary keys and tokens are becoming more widely adopted by AWS architects and engineers.  

Information: http://docs.aws.amazon.com/STS/latest/UsingSTS/Welcome.html

**Comment by iiro** [comment]
+1

Agree with @rcsavage - this is a very common pattern nowadays.

**Comment by dheerajd-msys** [comment]
@rcsavage , `--aws-session-token` option is added in latest `knife-ec2`. Closing this issue for now. Please feel free to re-open if any issue.
