### ISSUE TITLE
Allow search for EC2 AMIs

### ISSUE THREAD

**Issue by patcon** [chef/knife-ec2#313]
Would be nice if some official AMIs were easily available, so that usage instructions for simple use-cases would not involve of "look up ami names on community site" step :)

Related:
- https://github.com/test-kitchen/kitchen-ec2/blob/master/data/amis.json
- https://github.com/test-kitchen/kitchen-ec2/issues/117

**Comment by patcon** [comment]
Or perhaps simplest would be to allow a user to drop a `amis.json` or `amis.yml` file into the `.chef/` dir where the knife.rb exists.

**Comment by siddheshwar-more** [comment]
@patcon 
According to this reference https://github.com/test-kitchen/kitchen-ec2/issues/117#issuecomment-103604021 , adding the .json file won't help as aws changes AMI's Id.

Probably we can add new option something like `--image-name` in `knife-ec2`  which will take image name as a value. Example- "centos-6.4" and internally `knife-ec2` will find corresponding "ami-id" for specified image.

**Comment by btm** [comment]
Yes, this would be an AMI search like what was implemented in test-kitchen here: https://github.com/test-kitchen/kitchen-ec2/pull/17

**Comment by btm** [comment]
The MVP of this was released in knife-ec2 0.15. There's more work to do still in the next round.

**Comment by NimishaS** [comment]
@btm , can this issue be closed because the basic requirement is fulfilled in `knife-ec2 0.15.0`?
