### ISSUE TITLE
Release v0.11.0 via rubygems

### ISSUE THREAD

**Issue by patcon** [chef/knife-ec2#314]
Is this intentionally tagged but not released?

Thanks!

**Comment by patcon** [comment]
Also, why was rc0 tagged after the official v0.11?
https://github.com/chef/knife-ec2/releases

**Comment by NimishaS** [comment]
@patcon, that was by mistake. Deleted 0.11.0 tag. `knife-ec2` v0.11.0.rc.0 has been released on rubygems.
Thanks for informing this issue.

**Comment by patcon** [comment]
Thanks! But in the future, the semver way of doing things is technically to just move forward to 0.12.0 -- tagged releases, even accidental ones, should never disappear or change
