### ISSUE TITLE
Should support spot request type ?

### ISSUE THREAD

**Issue by chrisduong** [chef/knife-ec2#316]
Hi,

I'm glad that we can launch spot instance with knife ec2. However, the default type is one-time. I wonder if you guys can support  *persistent request* also. In some simple case, we might just need to use *persistent request*

Thanks a ton.

**Comment by siddheshwar-more** [comment]
@chrisduong - We are looking into this.
Thank you!

**Comment by Aliasgar16** [comment]
Working on this issue under PR https://github.com/chef/knife-ec2/pull/326.

-Thanks

**Comment by NimishaS** [comment]
Issue is fixed and merged in https://github.com/chef/knife-ec2/pull/326.
