### ISSUE TITLE
SSL Connect Errors

### ISSUE THREAD

**Issue by dannyybarra** [chef/knife-ec2#325]
We just upgraded to chef 12 and using chefdk 0.6.2-1. When issuing any knife ec2  commands I get the following error.
ERROR: Excon::Errors::SocketError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (OpenSSL::SSL::SSLError).

**Comment by dheerajd-msys** [comment]
@dannyybarra is this issue resolved?  Can you try using latest `Chefdkv0.19.6` ?

**Comment by btm** [comment]
Generally with errors like this we need to see the output of `knife server create ARGUMENTS -V -V` to be able to debug the issue.

**Comment by dheerajd-msys** [comment]
@dannyybarra, I hope above comments help you resolve issue. Please feel free to re-open if you still get errors. Thanks.
