### ISSUE TITLE
Command line options not taking priority over knife configuration

### ISSUE THREAD

**Issue by yoshiwaan** [chef/knife-ec2#328]
Hello,

I'm trying to spool an ec2 instance using knife ec2. I have the following set in my knife.rb
```
knife[:aws_ssh_key_id] = 'devop'
```
I am using a command similar to the following to spool up an instance:
```
/usr/bin/knife ec2 server create --image ami-1ecae776 --region us-east-1 --node-name asdf1234 --flavor m3.large --security-group-ids sg-asdf1234 --subnet subnet-asdf1234 --associate-public-ip --ebs-size 150 --ebs-volume-type gp2 --iam-profile webServer --bootstrap-version 12.4 --ssh-key dev --ssh-user ec2-user --identity-file ~/.ssh/dev.pem --secret-file ~/.chef/encrypted_data_bag_secret --run-list role[web-server] --environment development
```
Which produces the following output from knife:
```
Instance ID: i-95fc8946
Flavor: m3.large
Image: ami-1ecae776
Region: us-east-1
Availability Zone: us-east-1d
Security Group Ids: sg-asdf1234
IAM Profile: webServer
Tags: Name: asdf1234
SSH Key: devop
```
The keypair used in AWS is based on the value from knife.rb instead of a specifically defined command line parameter. Commenting out the line knife[:aws_ssh_key_id] = 'devop' in knife.rb yields the expected result, namely the keypair is set using the --ssh-key option.

The specific command line options should take precedence over knife.rb configuration options: https://tickets.opscode.com/browse/CHEF-1772
https://github.com/chef/knife-ec2/issues/247

I am using the latest version of Chef server.

**Comment by NimishaS** [comment]
@yoshiwaan, fix for this issue has been merged in master branch. Please verify.

**Comment by yoshiwaan** [comment]
Sorry for the delay.

That seems to have done the trick.

**Comment by yoshiwaan** [comment]
Is this released as a gem yet?

**Comment by NimishaS** [comment]
@yoshiwaan , this fix is not released yet. We'll have a release very soon.

**Comment by gbish** [comment]
Hey,

Have you heard about that really wowsome stuff? You won't regret, believe me, read more here <http://sykimordy.wednesdayfoodblogging.com/oiuqmcqq>

Good wishes, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hey,

I've got some good news for you, read more about it here <http://thifraslarda.thesocialdeviants.com/oihicr>

My best to you, hebgb@blueyonder.co.uk
