### ISSUE TITLE
Assumes external IP address in VPC must be from EIP

### ISSUE THREAD

**Issue by devdazed** [chef/knife-ec2#344]
This code:

``` rb
      def ssh_connect_host
        @ssh_connect_host ||= if config[:server_connect_attribute]
                                server.send(config[:server_connect_attribute])
                              else
                                if vpc_mode? && !config[:associate_public_ip]
                                  server.private_ip_address
                                else
                                  server.dns_name || server.public_ip_address
                                end
                              end
      end
```

Assumes that if the machine is in the VPC then it must be using an Elastic IP Address as it's external IP.  This means that when [auto-assign-public-ip-address](http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-ip-addressing.html#vpc-public-ip) is on, knife will not be able to connect because it will attempt to connect to the private IP address.

It seems I can work around this issue by adding `--server-connect-attribute public_ip_address`

**Comment by Vasu1105** [comment]
@devdazed 

In VPC mode normally people have their own Open Source chef server and knife workstation is installed on subnet and all node is talking to that chef server and nodes are easily accessible with private IP for knife-workstation, Thats why we are using private_ip as default when associate_ip is not used, and i think people don't use auto generated public ip in VPC normally thats why we gave second priority to public-ip and you are right there is option- server-connect-attribute public_ip that you can use in your case.

**Comment by btm** [comment]
@Vasu1105 I wonder if there's a presumption in that design that VPC is something people intentionally choose for a scenario where they want to create a private cloud in AWS? However, new AWS accounts only get EC2 VPC now, and cannot use "EC2 Classic."

> Accounts created after 2013-12-04 support EC2-VPC only. 

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_Introduction.html

This is another ticket, but I'm going to write it down here. We should document the possible values you can give `---server-connect-attribute`.  It looks like these are values from the [EC2 Instance Object](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Instance.html). I'd guess the

* private_dns_name
* private_ip_address
* public_dns_name
* public_ip_address

**Comment by siddheshwar-more** [comment]
@btm 
Yeah- we should document possible values of `---server-connect-attribute` in README!!!

And yeah if making `---server-connect-attribute` default to `public_ip_address`  is more usable than default private_ip then we can update existing flow? Could you please suggest your thoughts?

**Comment by btm** [comment]
To solve @devdazed's bug, we expand the conditional there. We currently determine VPC by if there's a subnet_id provided or not. This appears to be wrong, it appears that newer VPC only AWS account have a "default subnet" created, and you don't have to specify it. That's another separate bug.

Given that we know the subnet [at least for now], we can look up if that subnet has auto-assign-public-ip enabled with `connection.get(subnet_id).map_public_ip_on_launch`, which returns boolean. 

There's also an issue I've seen where we use `--associate-eip` instead of `--associate-public-ip` where I've had to specify the `--server-connect-attribute`. The logic to fix this bug and @devdazed's bug is probably this:

```
def subnet_public_ip_on_launch?
  connection.get(subnet_id).map_public_ip_on_launch
end

if config[:server_connect_attribute]
  server.send(config[:server_connect_attribute])
elsif vpc_mode? && !(subnet_public_ip_on_launch? || config[:associate_public_ip] || config[:associate_eip])
  server.private_ip_address
else
  server.dns_name || server.public_ip_address
end
```

Created #379 for the `--server-connect-attribute documentation`
Created #380 for allowing VPC without specifying a subnet if we have a default subnet

**Comment by gbish** [comment]
Hi,

Look at that, it's something really worthy, don't miss it. Here is the link  <http://peketunde.octazen.com/oizal>

My Best, hebgb@blueyonder.co.uk

**Comment by dheerajd-msys** [comment]
Fixed in https://github.com/chef/knife-ec2/pull/468

**Comment by NimishaS** [comment]
Fixed in https://github.com/chef/knife-ec2/pull/468
