### ISSUE TITLE
Support knife winrm on ec2 decrypting Admin password using public key used to create node

### ISSUE THREAD

**Issue by hh** [chef/knife-ec2#357]
```knife winrm name:windows2 --winrm-user 'Administrator' --winrm-password 'FOO' -a cloud.public_ipv4``` is currently requiring PASSWORD when connecting to windows nodes on ec2 even though the password is supplied from AWS and decryptable via the private key sude to create the node

We should be able to pass the ssh key used to create the node and retrieve it dynamically when using knife winrm via [AWS::EC2::Client#get_password_data](https://docs.aws.amazon.com/AWSRubySDK/latest/AWS/EC2/Client.html#get_password_data-instance_method) the way test-kitchen on chef-provisioning do by passing --ssh-key or something

The dynamically generated password also a command line to retrieve it: http://docs.aws.amazon.com/cli/latest/reference/ec2/get-password-data.html 

https://github.com/chef/chef-provisioning-aws/blob/64e23b6acae83a0417f06795b6c4b8812635e71a/lib/chef/provisioning/aws_driver/driver.rb#L832

```ruby
      Chef::Log.info "waiting for #{machine_spec.name}'s admin password to be available..."
      while time_elapsed < max_wait_time && encrypted_admin_password.nil?
        response = ec2.client.get_password_data({ :instance_id => instance_id })
        encrypted_admin_password = response['password_data'.to_sym]

        if encrypted_admin_password.nil?
          Chef::Log.info "#{time_elapsed}/#{max_wait_time}s elapsed -- sleeping #{sleep_time} for #{machine_spec.name}'s admin password."
          sleep(sleep_time)
          time_elapsed += sleep_time
        end
      end

      Chef::Log.info "#{machine_spec.name}'s admin password is available!"```

https://github.com/test-kitchen/kitchen-ec2/blob/b27f058ef9bfa28053966b8e7fe6d8a0bac38227/lib/kitchen/driver/ec2.rb#L406

```ruby
      # rubocop:disable Lint/UnusedBlockArgument
      def fetch_windows_admin_password(server, state)
        wait_with_destroy(server, state, "to fetch windows admin password") do |aws_instance|
          enc = server.client.get_password_data(
            :instance_id => state[:server_id]
          ).password_data
          # Password data is blank until password is available
          !enc.nil? && !enc.empty?
        end
        pass = server.decrypt_windows_password(instance.transport[:ssh_key])
        state[:password] = pass
        info("Retrieved Windows password for instance <#{state[:server_id]}>.")
      end```

**Comment by hh** [comment]
My alternative has been to create an admin user and specify that user/pass in kniferb:

```ruby
# create a user and put them in admin                                                                                                          
user "ChefAdmin" do                                                                                                                            
  password "p@ssw0rd"                                                                                                                          
end                                                                                                                                            
                                                                                                                                               
group "Administrators" do                                                                                                                      
  action :modify                                                                                                                               
  members "ChefAdmin"                                                                                                                          
  append true                                                                                                                                  end                                                                                                                                            
```

Which may be sufficient for most folks.

**Comment by NimishaS** [comment]
@hh , this is already implemented in `knife-ec2`. Please refer https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_server_create.rb#L1152-L1178.
So you can bootstrap your node without passing username and password like this:
```
knife ec2 server create -N <node-name> -I <image-id> -f m1.small --ssh-key <ssh-key-name> --bootstrap-protocol winrm --identity-file <path-to-ssh-key> -c chef-repo\.chef\knife.rb --groups <security-group>

**Comment by hh** [comment]
@NimishaS this isn't for knife ec2 server create, this is for knife winrm itself.

**Comment by hh** [comment]
I'd like to keep this one open for discussion if possible.

**Comment by siddheshwar-more** [comment]
@hh Thank you for suggestions!

I think this change need AWS EC2 specific API calls and then it becomes EC2 specific feature and integrating with generic `knife winrm` i.e `knife-windows` is not right place. As `knife winrm` is used to connect any windows VM, doesn't matter where it exists i.e on cloud or in-premises.

**Comment by NimishaS** [comment]
@hh , created https://github.com/chef/knife-windows/issues/319 to track this.

**Comment by hh** [comment]
I think it might be best to create a ```knife ec2 winrm``` command so we don't have a knife-windows dependencies on the winrm gem.

**Comment by gbish** [comment]
Hello,

I found the stuff we've discussed with you recently, get it here <http://hikitrasty.robprior.com/oiubyntg>
Very truly yours, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hi,

Have you heard fromour friends lately? You can read some news about them here <http://nkistentipu.collectiblecrystal.com/oiwjrugn>

Be well, hebgb@blueyonder.co.uk
