### ISSUE TITLE
VPC does not require a subnet to be specified

### ISSUE THREAD

**Issue by btm** [chef/knife-ec2#380]
As mentioned in #344, AWS accounts created after 2013-12-04 don't support "EC2 Classic" and just use VPC. These accounts have a default subnet created so you don't have to specify one. We should 
- find a different way to determine we are on VPC for #vpc_mode?
- ensure we raise an reasonable error (ourselves if the API doesn't) if VPC is the only supported platform, there is no default subnet, and the user has not passed a subnet.
- if vpc_mode? is true, we have a default subnet, but the user has not passed a subnet_id, populate subnet_id (so the solution in #344 can tell if auto-assign-ip is enable for that subnet).

**Comment by siddheshwar-more** [comment]
Hello @btm ,

This is very nice idea to use default vpc and subnet and find out auto-assing-ip intelligently for bootstrapping. 
We have below findings in-terms of use cases. Please have look and share your thoughts -  

1 . If account only supports `EC2-VPC` platform then existing knife-ec2 creates VM's in default VPC and Subnet.

2 . Consider if account supports both platform i.e EC2-VPC and EC2-CLASSIC. 
For this case we should have flag like `--select-aws-platform vpc(i.e default)  or classic` it will give choice to user to select platform. 

2.1 `--select-aws-platform VPC`
a. For this case by default VM will gets created in default VPC and Subnet. Validate does account supports VPC platform? and find default VPC id and Subnet id to create VM. 
  b. if `--subnet-id` specified then we will find corresponding VPC id and create VM in same. 
Note- By default, for both cases check auto-assign-public-ip is enabled.
 c. If default VPC is deleted and no --subnet-id specified. In this case raise an error.

2.2 `--select-aws-platform classic`
The VM will gets created in AWS Classic network.

Could you please comment on this.
Thank You.

**Comment by NimishaS** [comment]
@btm , please let us know your views on this.

**Comment by btm** [comment]
@NimishaS I suppose over time the number of people who still have classic accounts will decrease and new people will just have vpc with a default subnet and be less confused, but I'm a little surprised more people don't need a `--aws-platform` flag.

**Comment by harikesh-kolekar** [comment]
@btm,
 If the account supports only EC2-VPC platform then existing knife-ec2 creates VMs by using default VPC and Subnet.
We don't have EC2 classic account so we can't create the node on EC2 classic.
Can you please explain what needs to be fixed in this issue?

**Comment by btm** [comment]
2013-12-04 was a long time ago. Let's figure that everyone who has support for EC2 classic has figured this out, and everyone else will already have a default subnet with their VPC based EC2 account.
