### ISSUE TITLE
--create-no-ssl-listener should be --[no-]create-ssl-listner

### ISSUE THREAD

**Issue by btm** [chef/knife-ec2#381]
#363 added a --create-no-ssl-listener boolean flag, but this should be --create-ssl-listener so we also get --no-createl-ssl-listener through the magic of mixlib-cli.

(we should do this before release because #363 hasn't been released yet)

**Comment by Aliasgar16** [comment]
@btm Implemented the required changes here https://github.com/chef/knife-ec2/pull/390
