### ISSUE TITLE
Allow specifying the private ip address during `server create`

### ISSUE THREAD

**Issue by skarap** [chef/knife-ec2#396]
EC2 API allows one to chose the private ip address of an instance for EC2-VPC (http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html - see PrivateIpAddress parameter). Looks like the parameter is also supported by Fog.

That functionality would be very useful for me. And if there is interest in merging it, I can do the development.

**Comment by Vasu1105** [comment]
@skarap  This functionality is already in place for knife ec2. You can use --private-ip-address option for this.

**Comment by skarap** [comment]
My bad. Sorry for the noise.

**Comment by gbish** [comment]
Hey,

Here are some of my meditations on life and art, please read them and tell me what you think, here is the link <http://thiltathaxo.bohbotreg.com/oihumd>

Best regards, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hello,

I've came across that information yesterday and thought it would help you, read more here please <http://jerduslaphe.montessoriacademyofchicago.us/oiirss>

Typos courtesy of my iPhone, hebgb@blueyonder.co.uk
