### ISSUE TITLE
Missing support for --json-attribute-file in knife ec2 server create

### ISSUE THREAD

**Issue by neilsimon** [chef/knife-ec2#397]
Attributes overriden through --json-attribute-file seem to be ignored and there does not seem to be actual support for --json-attribute-file in the ec2_server_create.rb file

**Comment by dheerajd-msys** [comment]
@neilsimon, This issue is handled in the PR #400.

**Comment by btm** [comment]
This is fixed by #400, let us know if you have any further problems @neilsimon.
