### ISSUE TITLE
 ERROR: knife encountered an unexpected error

### ISSUE THREAD

**Issue by vgul** [chef/knife-ec2#401]
I got

ERROR: knife encountered an unexpected error
This may be a bug in the 'ec2 server create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `empty?' for nil:NilClass

log attached as
http://pastie.org/pastes/10703066/text?key=6i6mph7rsmfxaqqq6sv3gq

**Comment by gmiranda23** [comment]
I also encountered this error when not specifying a run_list.  Providing a run_list seems to resolve the issue.  If you have no run_list to provide, a workaround currently appears to be to provide a blank run_list (e.g. ``knife ec2 server create [settings] -r ''``)

**Comment by gbish** [comment]
Hello,

I've came across that information yesterday and thought it would help you, read more here please <http://githerdycra.anitaspottery.com/oivmpssb>

Sincerely, hebgb@blueyonder.co.uk

**Comment by btm** [comment]
This is a dupe of https://github.com/chef/knife-ec2/issues/370, which is fixed in knife-ec2 0.13.0, released on 8/8/16.
