### ISSUE TITLE
Why are tags added after the instance is started?

### ISSUE THREAD

**Issue by techjanitor** [chef/knife-ec2#402]
This decision seems kind of inexplicable to me, considering the Name tag is added prior. What is the reason? This is causing a weird timing issue using the new CloudWatch events API. You can set an event to trigger when an instance transitions to the 'Running' state, but when that happens the tags won't necessarily be on the host.

https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_server_create.rb#L512

**Comment by btm** [comment]
I don't recall the specifics, but years ago Fog had an issue with creating tags too early. We made various changes to handle those cases, see http://tickets.chef.io/browse/KNIFE-207 for history.

I don't know what you mean about the Name tag being added prior, unless that's being done by Fog. We create all the tags at once in the call to `create_tags` here: https://github.com/chef/knife-ec2/blob/90f5c30fcbeb234f1d9e17273726503b0c8060d3/lib/chef/knife/ec2_server_create.rb#L541

I'm going to close out this issue for now, but if you have more specific information to provide please let us know.
