### ISSUE TITLE
encrypted data bag secret file does not get copied to windows machines

### ISSUE THREAD

**Issue by mwalton236** [chef/knife-ec2#403]
When using knife-ec2 0.12.0 and knife-windows 1.2.0, the encrypted data bag secret file is not copied to the windows client, if it's set using --secret-file or knife[:bootstrap][:secret_file].

knife-windows expects the contents of the secret_file to be loaded into bootstrap.config[:secret]

**Comment by dheerajd-msys** [comment]
@mwalton236 , I verified `--secret-file` option on windows. The encrypted data bag secret file does get copied to `C:\chef\encrypted_data_bag_secret` and it's reference gets added to the `client.rb` file.

This seems to be working fine

**Comment by mwalton236** [comment]
What command did you use to attempt to replicate the problem.

knife bootstrap windows does work with --secret-file
knife ec2 server create does not work with --secret-file for a windows machine

**Comment by NimishaS** [comment]
Merged https://github.com/chef/knife-ec2/pull/409 in master branch.
@mwalton236 , please check. Closing this issue.

**Comment by gbish** [comment]
Hello,

This is what you were looking for, this information may be useful for you, read more at <http://tagykary.jenbaker.org/oivbsf>

Faithfully, hebgb@blueyonder.co.uk
