### ISSUE TITLE
--security-group-ids

### ISSUE THREAD

**Issue by darrylb-github** [chef/knife-ec2#406]
I can't seem to get this param to work trying multiple formats:

`--security-group-ids '[sg-e985168d,sg-e7f06383,sg-ec1b7e88]'`
`--security-group-ids 'sg-e985168d,sg-e7f06383,sg-ec1b7e88'`
`--security-group-ids sg-e985168d,sg-e7f06383,sg-ec1b7e88`

This is when making a spot instance request in a VPC subnet. 

Every time it defaults back to the default security group. The security group IDs are definately correct and exist in the VPC listed.

Any ideas what I'm doing wrong?

Full command:
`knife ec2 server create -x 'centos' -i '~/.ssh/work-aws'  -N 'Staging_Skeleton' -r 'role[qa-staging-skeleton],' -E 'staging' -j '{ "name": "Staging_Skeleton" }' --flavor 'm3.medium' --spot-price '0.1' --ssh-key 'work-aws' --subnet 'subnet-363d446f' --security-group-ids '[sg-e985168d,sg-e7f06383,sg-ec1b7e88]' --ebs-volume-type 'gp2' --ebs-size '40' --iam-profile 'chef-client' --associate-public-ip'`

Thanks,
Darryl

**Comment by dheerajd-msys** [comment]
Hi @darrylb-github ,
Format for providing the security group ids is `--security-group-ids 'sg-e985168d,sg-e7f06383,sg-ec1b7e88'` .

Please verify if your spot price request is fulfilled.

**Comment by NimishaS** [comment]
@darrylb-github, did the solution work for you?

**Comment by appanchor** [comment]
I had the same issue. Surrounding the Security Group IDs with single quotes worked. It would be great if --help indicated this. 

--security-group-ids 'X,Y,Z'

**Comment by Vasu1105** [comment]
@appanchor  will update the help for this.

**Comment by btm** [comment]
We're discussing in https://github.com/chef/knife-ec2/pull/439 switching to `--security-group-ids sg-e985168d --security-group-ids sg-e7f06383 --security-group-ids sg-ec1b7e88` or `-g sg-e985168d -g sg-e7f06383 -g sg-ec1b7e88` to avoid issues with comma separated values. 

We can keep supporting 'x,y,z' too depending on how much code there is to support that.

**Comment by Vasu1105** [comment]
@btm we have fixed the issues related multiple security group ids here #439. Its still not released.  Should we close this one ?

**Comment by btm** [comment]
This has been released in knife-ec2 0.14.0

https://discourse.chef.io/t/knife-ec2-0-14-0-released/9972

**Comment by btm** [comment]
As per https://github.com/chef/knife-ec2/issues/406#issuecomment-238940775, in https://github.com/chef/knife-ec2/pull/439, we added a new `--security-group-id` option that allows you to use the argument multiple times. This behavior is more consistent across our tools and avoids having to parse different string delimiters.
