### ISSUE TITLE
knife ec2 server create using AMI with secondary encrypted EBS volume fails to launch

### ISSUE THREAD

**Issue by rfackett** [chef/knife-ec2#410]
When launching an AWS EC2 instance using knife ec2 server create and using an AMI that contains a secondary EBS volume which is encrypted (using EBS encryption), the EC2 instance immediately goes to terminated state (the knife command then times out waiting for the instance which never goes available).  This is using the current version of knife-ec2 gem and chefdk.

This was previously working for us using the same AMI, though it has been a few months (possibly 6) since we last launched a server using this AMI.  We also tried creating a new base AMI from scratch to replicate the problem, and it did in fact persist to the new AMI.  We then created another new AMI that was using an unencrypted secondary EBS volume and that launched successfully.  I have not tested this yet using an encrypted root EBS volume AMI, though we do plan to test this in the near future.

Manually launching the AMI within the AWS console does not have any issues.  In a support ticket with AWS they found the following:  I (AWS) checked all the failed instance that you have attempted to launch using the command (knife ec2 server create) and I was able to find a common pattern of error on each of the instances that failed to boot. The error basically states that the secondary encrypted volume does not exists on each of these instances.

Since this AMI launches within AWS but not via knife ec2 server create, I believe the issue lies with the knife ec2 gem.

**Comment by sean-horn** [comment]
This issue happens with chefDK 0.11.2 and knife-ec2-0.12.0

**Comment by dheerajd-msys** [comment]
@rfackett 
To reproduce the error I tried to create encrypted EBS volume and attached the volume to an already existing EC2 instance and created an Image out of it.
Used the same image and then tried to create the new server from `knife ec2 server create`.
We can see the server running in AWS console with attached EBS volume. However bootstrap is failing with below error :
```
ec2-52-90-251-143.compute-1.amazonaws.com Authentication Error:
ec2-52-90-251-143.compute-1.amazonaws.com ---------------------
ec2-52-90-251-143.compute-1.amazonaws.com Failed to authenticate to the chef server (http 401).
ec2-52-90-251-143.compute-1.amazonaws.com
ec2-52-90-251-143.compute-1.amazonaws.com Server Response:
ec2-52-90-251-143.compute-1.amazonaws.com ----------------
ec2-52-90-251-143.compute-1.amazonaws.com Failed to authenticate as 'dh1'. Ensure that your node_name and client key are correct.
ec2-52-90-251-143.compute-1.amazonaws.com
ec2-52-90-251-143.compute-1.amazonaws.com Relevant Config Settings:
ec2-52-90-251-143.compute-1.amazonaws.com -------------------------
ec2-52-90-251-143.compute-1.amazonaws.com chef_server_url   "https://api.opscode.com/organizations/nimisha"
ec2-52-90-251-143.compute-1.amazonaws.com node_name         "dh1"
ec2-52-90-251-143.compute-1.amazonaws.com client_key        "/etc/chef/client.pem"
ec2-52-90-251-143.compute-1.amazonaws.com
ec2-52-90-251-143.compute-1.amazonaws.com If these settings are correct, your client_key may be invalid,
```
Are you getting the same error using `knife ec2 server create` command?
We also tried from the portal and the VM spawned successfully.

Also please share what command did you use to create the server.

**Comment by rfackett** [comment]
My experience is different.  If I launch my AMI (with unencrypted root volume and encrypted secondary volume) via the AWS console, the instance launches without issue.

If I run the following knife ec2 server create command using the same AMI, I don't get an error specifically within knife ec2, I simply get a timeout in knife ec2 waiting to connect to the AWS instance.  The reason the timeout occurs is the AWS instance is in a terminated state.  I am not sure what part of the workflow is terminating the AWS instance, but that is why the knife ec2 command finally times out.  In this console output I terminated the job manually as the AWS instance was terminated, but you get the idea.

PS C:\Users\fackettr\keys> knife ec2 server create --image ami-74b25e14 --flavor m3.medium --region us-west-2 --subnet subnet-893e7aec --security-group "sg-932b80f4,sg-912b80f6,sg-1a23887d" --iam-profile ec2_power_user --private-ip-address 10.250.42.22 --ssh-key fhlbsf-dr --ssh-user ubuntu --identity-file fhlbsf-dr.pem --node-name "dr-awplmcmweb01" --run-list "role[collateral]" --environment mockdr_mcm --fqdn dr-awplmcmweb01.fhlbsf-i.com --tags "Project=MCM,Environment=MockDR 
,Function=Tomcat Web Server,Cost Center=330" --bootstrap-version 12.6.0-1 --secret-file encrypted_data_bag_secret_dr_mcm

Instance ID: i-c095e207 
Flavor: m3.medium 
Image: ami-74b25e14 
Region: us-west-2 
Availability Zone: us-west-2a 
Security Group Ids: sg-932b80f4, sg-912b80f6, sg-1a23887d 
IAM Profile: ec2_power_user 
Tags: Project: MCM, Environment: MockDR, Function: Tomcat Web Server, Cost Center: 330, Name: dr-awplmcmweb01 
SSH Key: fhlbsf-dr

Waiting for EC2 to create the instance.............Terminate batch job (Y/N)? Y 
PS C:\Users\fackettr\keys>

**Comment by rfackett** [comment]
I tested this again using an AMI with a single root volume that was encrypted and it exhibits the same behavior.  The EC2 instance is immediately terminated after is created by knife ec2 server create.   This same AMI launches fine from with the AWS console.

It would seem the timing may be related to AWS EBS encryption using KMS instead of just built in EBS encryption (with no user defined key).  Perhaps this is an area worth focusing on?  The EBS value for Encrypted is either "Encrypted" or "Not Encrypted".  If the value is "Encrypted", it also has KMS details for "KMS Key Alias" and "KMS Key ARN".  Prior to KMS, I am not sure what the EBS Encryption value was, it could have simply been True or False?

An alternative theory would be some kind of access restriction to KMS, but I believe knife ec2 uses the user AWS credentials, so that would suggest the problem launching would be the same within the console as it would using knife ec2 (assuming the same security configuration).

**Comment by dheerajd-msys** [comment]
@rfackett, I tried the command given below with an image containing encrypted secondary volume.
```
knife ec2 server create -I ami-f9e4e293 -f t2.micro -x 'ubuntu' --ssh-key nimec2 -c D:\chef-starter\chef-repo\.chef\knife.rb --identity-file D:\chef-starter\chef-repo\.chef\nimec2.pem -N testebsdh4
```
The command ran successfully. Can you try running the same command that is mentioned above and skip other parameters?
We have tried with both `chef-client` and `chef-dk`. We were using the `master` branch of `knife-ec2`.

**Comment by rfackett** [comment]
@dheerajd-msys I am not able to run the command exactly like you stated as we do not have a default VPC set, so we have to specify the subnet.  I added the security groups as without them, I would not be able to SSH to continue the chef run.  Here are both outputs.  In the second ec2 knife server create command with the minimum options using the AMI with encrypted EBS, the EC2 instance still comes up terminated right away (same behavior):

PS C:\Users\fackettr\keys> knife ec2 server create -I ami-b109e5d1 -f t2.micro -x 'ubuntu' --ssh-key fhlbsf-dev -c C:\Us
ers\fackettr\keys\knife.rb --identity-file C:\Users\fackettr\keys\fhlbsf-dev.pem -N cheftest
ERROR: Fog::Compute::AWS::Error: VPCIdNotSpecified => No default VPC for this user
PS C:\Users\fackettr\keys>
PS C:\Users\fackettr\keys> knife ec2 server create -I ami-b109e5d1 -f t2.micro --subnet subnet-953e7af0 --security-group
"sg-0957f66d,sg-0857f66c,sg-a90ba0cd" -x 'ubuntu' --ssh-key fhlbsf-dev -c C:\Users\fackettr\keys\knife.rb --identity-fi
le C:\Users\fackettr\keys\fhlbsf-dev.pem -N cheftest
Instance ID: i-2e440ee9
Flavor: t2.micro
Image: ami-b109e5d1
Region: us-west-2
Availability Zone: us-west-2a
Security Group Ids: sg-0957f66d, sg-0857f66c, sg-a90ba0cd
Tags: Name: cheftest
SSH Key: fhlbsf-dev
 
Waiting for EC2 to create the instance.......Terminate batch job (Y/N)? Y
PS C:\Users\fackettr\keys>

**Comment by Aliasgar16** [comment]
Hi @rfackett 

I tried several things from my side to reproduce the issue that you are facing but unfortunately I could not reproduce the issue and things worked fine for me, below is the summary for the same:

**A. Steps for AMI image creation and knife ec2 server creation**

- Launched an ec2 instance with root volume unencrypted and secondary volume as encrypted.
- Created an AMI image from the instance created above.
- Used that same AMI image in knife ec2 server create command and it worked without any issue.

**Note:** For Amazon EBS encryption I used the default AWS Key Management Service (AWS KMS).


**B. Tried various permutations and combinations while creating an ec2 instance through knife ec2 like**

- Created my own VPC and Subnet and used them while creating instance through knife ec2.
- Tried to conflict the address range supported under the subnet to see if that could cause ec2 to terminate the instance but Fog (internally used by knife-ec2 gem to talk to various cloud providers) caught me at the very initial stage only.
- Also created my own IAM profile with very limited permissions to see if the permissions are causing the issue but did not got the behavior as you are experiencing.
- Tried giving different subnet (different from the one using which the base instance was created and then AMI image was created out of it) while knife ec2 server create, but got no success.
- Tried with basic/limited options with default VPC and default Subnet but got the same result.


**C. Did some research on why an ec2 instance would go to terminate state immediately after launch and got one link**

Click [here](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_InstanceStraightToTerminated.html)

- This link states 3 reasons for instance to go in terminate instance immediately after its launch, but I am not sure whether this is applicable to you because as per your comments things worked fine for you through ec2 portal.


So is it possible for you to share with me the complete flow that you followed while ec2 instance, EBS volume, AMI image creation, knife ec2 server creation, etc. along with the supporting commands and some useful logs.

This would help me to first replicate the problem on my end, diagnose and locate the root cause for its rectification.

Please let me know your response.

Thanks

**Comment by rfackett** [comment]
@Aliasgar16 
Thank you for taking the time to run through all these steps.  Here is a detailed list of what we have done to arrive at the current state.

1. We have been launching EC2 instances for the last year using knife ec2 server create with one of two AMIs, the only difference being the mount point of the secondary encrypted EBS volume.  1 AMI uses /usr/local/member, the other AMI uses /usr/local/mcm.  We don't create servers with these AMIs very often, the last one we launched using this AMI was February 1, 2016. The details of the AMIs are as follows:
Creation date = February 23, 2015 9:48:17 PM
Virtualization = hvm
Root Device Type = ebs
Platform = Ubuntu (14.04 LTS in us-west-2 generic AMI was the source we started with)
Block Devices = /dev/sda1=snap-2c7f53ac:8:true:gp2, /dev/sdb=snap-2f7f53af:50:true:gp2:encrypted

2. When we attempted to launch a set of new services in a new environment using the same AMI, we noticed the problem described above.  This was a couple weeks ago.  We opened a Chef support ticket and created this knife ec2 Github issue.

3) I then created a brand new AMI using the us-west-2 Ubuntu 14.04 LTS AMI (ami-9abea4fb).  I used the following steps:
3a) Launch ami-9abea4fb using the AWS console
3b) Attach an EBS volume of size 50GB and enable encryption
3c) sudo apt-get update && sudo apt-get upgrade
3d) sudo fallocate -l 1G /swapfile
3e) sudo mkswap /swapfile
3f) sudo swapon /swapfile
3g) sudo mkdir /usr/local/member
3h) sudo mkfs /dev/xvdb
3i) sudo mount /dev/xvdb /usr/local/member
3j) sudo vi /etc/fstab added the following two lines:
/dev/xvdb /usr/local/member ext4 defaults,nobootwait,noatime 0 0
/swapfile none swap sw 0 0
3k) Within the AWS console, I clicked on my instance and selected Actions --> Image --> Create Image

4) Once the AMI completed, I ran this knife ec2 server create command
knife ec2 server create --image ami-b109e5d1 --flavor m3.medium --region us-west-2 --subnet subnet-893e7aec --security-group "sg-932b80f4,sg-912b80f6,sg-1a23887d" --iam-profile ec2_power_user --private-ip-address 10.250.42.22 --ssh-key fhlbsf-dr --ssh-user ubuntu --identity-file fhlbsf-dr.pem --node-name "dr-awplmcmweb01" --run-list "role[collateral]" --environment mockdr_mcm --fqdn dr-awplmcmweb01.fhlbsf-i.com --tags "Project=MCM,Environment=MockDR,Function=Tomcat Web Server,CostCenter=330" --bootstrap-version 12.6.0-1 --secret-file encrypted_data_bag_secret_dr_mcm

5) The instance launches, here is the console output from knife ec2:
Instance ID: i-9689df51
Flavor: m3.medium
Image: ami-b109e5d1
Region: us-west-2
Availability Zone: us-west-2a
Security Group Ids: sg-932b80f4, sg-912b80f6, sg-1a23887d
IAM Profile: ec2_power_user
Tags: Project: MCM, Environment: MockDR, Function: Tomcat Web Server, CostCenter: 330, Name: dr-awplmcmweb01
SSH Key: fhlbsf-dr
 
Waiting for EC2 to create the instance.........Terminate batch job (Y/N)? Y

6) If you go the AWS console, the instance is terminated and here is the reason provided in the Description:
State transition reason = Server.InternalError: Internal error on launch


I then created a new AMI using all the same settings described above but did NOT choose encrypted for the secondary EBS volume and it launched like normal.

**Comment by Aliasgar16** [comment]
Hi @rfackett 

I followed the exact same steps as you mentioned in your last comment, but I did not got any failure and things worked fine for me.

Digging more into the termination error message (Internal error on launch) brought me to below mentioned links:

Click [link 1](https://forums.aws.amazon.com/thread.jspa?threadID=89309)
Click [link 2](https://github.com/jtriley/StarCluster/issues/288) 
Click [link 3](https://github.com/jtriley/StarCluster/issues/329) 
Click [link 4](https://scn.sap.com/thread/3656645) 

The one possible issue might be that the EBS drive had did not cleanly detach from a running instance and so while launching a new instance it sees the drive as `in-use`, detach and re-attach could solve this kind of problem.

Can you also check whether your storage limit has exhausted or not, because it may disallow your request for more storage until you increase your account's storage limit.

Some links also suggested that this issue is region specific, so I even tried running the complete operation in different regions but I did not got any failure, things worked successfully in each of the scenarios.

Please let me know if any of this helps.

Thanks

**Comment by adamedx** [comment]
Also @sean-horn, have you been able to reproduce this? If so, we should debug with you.

**Comment by sean-horn** [comment]
@adamedx I have not reproduced the pre-created image issue. I may have some time to do that today.

@rfackett This workaround works fine with Chef 12.7.2 from ChefDK 0.11.2 + knife-ec2 0.12.0
You would just need to add a recipe for formatting and mounting the additional encrypted device which is generated during provisioning with the combined options `--ebs-encrypted --ebs-size 2`.

The 2GB encrypted EBS volume shows up as an additional device at /dev/xvdb.

```
knife ec2 server create -I ami-9abea4fb -f m3.medium --region us-west-2 --ssh-user ubuntu --identity-file ~/certificates/horns.pem -S horns -g sg-e602de83 -N staging-web-10 --ebs-encrypted --ebs-size 2 --server-connect-attribute public_ip_address --use-sudo-password

... other bootstrap output

52.38.55.8 Preparing to unpack .../chef_12.8.1-1_amd64.deb ...
52.38.55.8 Unpacking chef (12.8.1-1) ...
52.38.55.8 Setting up chef (12.8.1-1) ...
52.38.55.8 Thank you for installing Chef!
52.38.55.8 Starting the first Chef Client run...
52.38.55.8 Starting Chef Client, version 12.8.1
52.38.55.8 Creating a new client identity for staging-web-10 using the validator key.
52.38.55.8 resolving cookbooks for run list: []
52.38.55.8 Synchronizing Cookbooks:
52.38.55.8 Installing Cookbook Gems:
52.38.55.8 Compiling Cookbooks...
52.38.55.8 [2016-03-21T17:41:41+00:00] WARN: Node staging-web-10 has an empty run list.
52.38.55.8 Converging 0 resources
52.38.55.8
52.38.55.8 Running handlers:
52.38.55.8 Running handlers complete
52.38.55.8 Chef Client finished, 0/0 resources updated in 05 seconds

after before bootstrap

Instance ID: i-c6e5bb01
Flavor: m3.medium
Image: ami-9abea4fb
Region: us-west-2
Availability Zone: us-west-2a
Security Groups: default
Security Group Ids: sg-e602de83
Tags: Name: staging-web-10
SSH Key: horns
Root Device Type: ebs
Root Volume ID: vol-62bfd094
Root Device Name: /dev/sda1
Root Device Delete on Terminate: true

Block devices
===========================
Device Name: /dev/sda1
Volume ID: vol-62bfd094
Delete on Terminate: true

Device Name: /dev/sdb
Volume ID: vol-32bfd0c4
Delete on Terminate: true

===========================
Public DNS Name: ec2-52-38-55-8.us-west-2.compute.amazonaws.com
Public IP Address: 52.38.55.8
Private DNS Name: ip-172-31-36-192.us-west-2.compute.internal
Private IP Address: 172.31.36.192
Environment: _default
```

**Comment by sean-horn** [comment]
I did the same thing as above using the same versions, but this time, the source AMI ami-a3d53dc3 was a direct copy of the above system, after I deleted /etc/chef/client.pem, so it wouldn't get in the way when trying to bootstrap. I cannot reproduce the failure..

```
shorn:sean-horn-opscode sean$ knife ec2 server create -I ami-a3d53dc3 -f m3.medium --region us-west-2 --ssh-user ubuntu --identity-file ~/certificates/horns.pem -S horns -g sg-e602de83 -N check-image-creation --server-connect-attribute public_ip_address --use-sudo-password

Instance ID: i-ef0c5528
Flavor: m3.medium
Image: ami-a3d53dc3
Region: us-west-2
Availability Zone: us-west-2a
Security Group Ids: sg-e602de83
Tags: Name: check-image-creation
SSH Key: horns

Waiting for EC2 to create the instance......
Public DNS Name: ec2-52-38-11-160.us-west-2.compute.amazonaws.com
Public IP Address: 52.38.11.160
Private DNS Name: ip-172-31-35-13.us-west-2.compute.internal
Private IP Address: 172.31.35.13

Waiting for sshd access to become available
done

Doing old-style registration with the validation key at /Users/sean/src/ocs/sean-horn-opscode/.chef/sean-horn-opscode-validator.pem...
Delete your validation key in order to use your user credentials instead

Connecting to 52.38.11.160
52.38.11.160 -----> Existing Chef installation detected
52.38.11.160 Starting the first Chef Client run...
52.38.11.160 Starting Chef Client, version 12.8.1
52.38.11.160 Creating a new client identity for check-image-creation using the validator key.
52.38.11.160 resolving cookbooks for run list: []
52.38.11.160 Synchronizing Cookbooks:
52.38.11.160 Installing Cookbook Gems:
52.38.11.160 Compiling Cookbooks...
52.38.11.160 [2016-03-21T18:26:34+00:00] WARN: Node check-image-creation has an empty run list.
52.38.11.160 Converging 0 resources
52.38.11.160
52.38.11.160 Running handlers:
52.38.11.160 Running handlers complete
52.38.11.160 Chef Client finished, 0/0 resources updated in 04 seconds

Instance ID: i-ef0c5528
Flavor: m3.medium
Image: ami-a3d53dc3
Region: us-west-2
Availability Zone: us-west-2a
Security Groups: default
Security Group Ids: sg-e602de83
Tags: Name: check-image-creation
SSH Key: horns
Root Device Type: ebs
Root Volume ID: vol-a397f855
Root Device Name: /dev/sda1
Root Device Delete on Terminate: true

Block devices
===========================
Device Name: /dev/sda1
Volume ID: vol-a397f855
Delete on Terminate: true

Device Name: /dev/sdb
Volume ID: vol-6897f89e
Delete on Terminate: true

===========================
Public DNS Name: ec2-52-38-11-160.us-west-2.compute.amazonaws.com
Public IP Address: 52.38.11.160
Private DNS Name: ip-172-31-35-13.us-west-2.compute.internal
Private IP Address: 172.31.35.13
Environment: _default
```

The encrypted volume /dev/xvdb is mounted when I login and check.

```
root@ip-172-31-35-13:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G   12K  1.9G   1% /dev
tmpfs           377M  328K  377M   1% /run
/dev/xvda1      7.8G  996M  6.4G  14% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            1.9G     0  1.9G   0% /run/shm
none            100M     0  100M   0% /run/user
/dev/xvdb       2.0G  3.0M  1.9G   1% /usr/local/member
```

**Comment by rfackett** [comment]
@Aliasgar16 
Thank you for the research on this!  Sorry for the delay in responding.

I checked the EBS storage limits, they are as such in our region:
EBS Active Volumes = 110/5000
EBS Active Snapshots = 2522/10000
EBS Magnetic GiB = 1130/20480
EBS General Purpose GiB = 9128/20480

Based on the above limits, I don't think we are running into any capacity issues in AWS EBS in our region.

I launched the two EBS volume AMI with the encrypted secondary volume using the AWS console (no issues/errors).  I stopped the instance, then I detached the encrypted secondary volume and waited for the status to go to available (from in-use).  I then created a new AMI using the stopped instance with detached encrypted secondary volume.

I proceeded to launch the new AMI in the same VPC + Subnet + Security Groups + Key as the manually launched AMI I created the AMI off of in the AWS Console (which has no issues launching the AMI), using the following knife command which finished successfully:

PS C:\Users\fackettr\keys> knife ec2 server create --image ami-253dd545 --flavor t2.micro --region us-west-2 --subnet subnet-1a942b43 --security-group "sg-0957f66d,sg-0857f66c,sg-4607ac22" --iam-profile ec2_power_user --ssh-key fhlbsf-dev -ssh-user ubuntu --identity-file fhlbsf-dev.pem --node-name "awdltestknife" --fqdn awdltestknife.fhlbsf-i.com --bootstrap-version 12.6.0-1


However, since the second EBS volume was detached, the AMI only included the root volume which is unencrypted, so that workflow doesn't really solve the original issue when using the encrypted EBS volumes.

Next I spun up an AMI using a single encrypted root volume using the AWS console.  I stopped the instance but left the volume attached and in-use.  I tried to launch this AMI via knife ec2 using the same command as above but with the new AMI ID, the result being the same failure, the instance comes up Terminated.

Next, I detached the encrypted root EBS volume from the stopped EC2 instance that the AMI is based off of.  I re-ran the same last knife ec2 server create command, the result being the same failure, the instance comes up Terminated.

Next, I created an AMI from a snapshot of the detached encrypted root EBS volume from previously and re-ran the same knife ec2 server create command with the new AMI ID, the result being the same failure, the instance comes up Terminated.

Lastly, I detached the volume from the stopped EC2 instance, then attached it back as the root device, created an AMI from that stopped with re-attached volume EC2 instance, then used the same knife ec2 server create command with the new AMI, the instance comes up Terminated.


 @sean-horn 
 Thanks for the work-around, though I still don't understand why this used to work for us, and now it does not.  I can work on modifying our base recipe to handle the volume stuff, but realluy, now that AWS supports encrypted root AMIs, I'd rather just use a single EBS volume that is encrypted.  My above testing does not support that feature in knife ec2 though.

 I will see if I can reproduce the issue using a different AWS account.

**Comment by rfackett** [comment]
as a side note, using the AWS CLI (aws ec2 run-instances) to launch the AMI also works without issue.

**Comment by rfackett** [comment]
i decided to test this using the AWS CLI (aws ec2 run-instances) and I am having the same issue, I am opening a new ticket with AWS as this is likely related.

**Comment by rfackett** [comment]
This can be closed.  Our issue was not related to knife ec2, but rather non-console API calls specifically using encrypted EBS volume AMIs and a security policy that was applied to protect access key usage.  I have a support ticket with AWS to determine what specifically is going on that created this unique condition.

Thank you @sean-horn / @Aliasgar16 / @adamedx / @dheerajd-msys for your time on this, greatly appreciate all the assistance.

**Comment by gbish** [comment]
Hi,

I've came across that new amazing stuff, don't miss it up! Just take a look here <http://hajivuspy.bestplanbforu.org/oifih>

Sent from my iPhone, hebgb@blueyonder.co.uk

**Comment by gbish** [comment]
Hello,
I'm so excited to tell you that,  I was impressed so much, please read here <http://nkuchocroja.floridacitygames.com/oieyk>

All the best, hebgb@blueyonder.co.uk
