### ISSUE TITLE
Hostname and FQDN

### ISSUE THREAD

**Issue by adiri** [chef/knife-ec2#412]
I'm not sure if it's a bug or this is the way it designed to work but when I server create -N whatever --fqdn whatever.where.ever it's not setting the machines hostname.

**Comment by btm** [comment]
The `--fqdn` option is only use for passing the fqdn for Kerberos Authentication. We should update the option description.

If you want to set the hostname you should use a cookbook, e.g. https://supermarket.chef.io/cookbooks/hostname

**Comment by dheerajd-msys** [comment]
Thanks @btm. We will add the description accordingly.

**Comment by NimishaS** [comment]
The description of -fqdn is updated in https://github.com/chef/knife-ec2/pull/466. Closing this issue.
