### ISSUE TITLE
Please release a new gem

### ISSUE THREAD

**Issue by jharveysmith** [chef/knife-ec2#417]
Hello,
The last gem was released Oct 2015 and changes have been merged since then (including https://github.com/chef/knife-ec2/pull/395 which we need).

Can you please release a new gem so we can use the more recent code?  Thanks.

**Comment by shortdudey123** [comment]
@NimishaS can you look into this :)

**Comment by Vasu1105** [comment]
@adamedx  your views on it

**Comment by btm** [comment]
0.13.0 was released on 8/8.

https://discourse.chef.io/t/knife-ec2-0-13-0-released/9100
