### ISSUE TITLE
ami_block_device_mappings support

### ISSUE THREAD

**Issue by lioramilbaum** [chef/knife-ec2#418]
Is the plugin supports ami_block_device_mappings settings?
I want to create an instance with root device larger from the default.  What is the best practice for my use case?

Thanks,
Liora

**Comment by dheerajd-msys** [comment]
Hi @lioramilbaum,

Currently plugin doesn't support ami_block_device_mappings settings.
For creating the root device larger than the default, probably the image will have to be created as per that and then using that image, create an instance.
