### ISSUE TITLE
Allow setting disable-api-termination

### ISSUE THREAD

**Issue by isaacdd** [chef/knife-ec2#419]
Looks like this has been reported a long time ago and supposedly been resolved (https://tickets.opscode.com/browse/KNIFE-165), but not seeing this option.

**Comment by Aliasgar16** [comment]
Added support for the `disable-api-termination` option in `knife-ec2`, here's the [PR](https://github.com/chef/knife-ec2/pull/427).

**Comment by isaacdd** [comment]
@Aliasgar16 thanks!

**Comment by btm** [comment]
This should be in 0.13.0.

https://discourse.chef.io/t/knife-ec2-0-13-0-released/9100
