### ISSUE TITLE
Unable to bootstrap and ends with exception: Exception: NoMethodError: undefined method `empty?' for nil:NilClass

### ISSUE THREAD

**Issue by ShadySQL** [chef/knife-ec2#421]
Tinocos-MacBook-Pro:.chef sabio$ 

knife ec2 server create -I ami-f95ef58a --ssh-key resourcevpc_rt -f t2.medium --ssh-user ubuntu --identity-file /Users/sabio/Downloads/resourcevpc_rt.pem

Instance ID: i-0b5247eadc5c35c83
Flavor: t2.medium
Image: ami-f95ef58a
Region: eu-west-1
Availability Zone: eu-west-1c
Security Groups: default
Tags: Name: i-0b5247eadc5c35c83
SSH Key: resourcevpc_rt

Waiting for EC2 to create the instance.....
Public DNS Name: ec2-52-208-104-125.eu-west-1.compute.amazonaws.com
Public IP Address: 52.208.104.125
Private DNS Name: ip-172-31-19-251.eu-west-1.compute.internal
Private IP Address: 172.31.19.251

Waiting for sshd access to become availabledone
ERROR: knife encountered an unexpected error
This may be a bug in the 'ec2 server create' knife command or plugin
Please collect the output of this command with the `-VV` option before filing a bug report.
Exception: NoMethodError: undefined method `empty?' for nil:NilClass

**Comment by Aliasgar16** [comment]
@ShadySQL can you provide detailed logs for the above command using `-VV` option ?

**Comment by Aliasgar16** [comment]
@ShadySQL gentle reminder to provide the required details.
