### ISSUE TITLE
Unable to access the New aws region India(ap-south-1)

### ISSUE THREAD

**Issue by Rijuvv** [chef/knife-ec2#422]
When i tried to access the ec2 resources in aws India(ap-south-1) region, it is showing the error "unknown region".

> ERROR:`  ArgumentError: Unknown region: "ap-south-1"

**Comment by dheerajd-msys** [comment]
@Rijuvv,
I found that with `knife-ec2` released version, the `fog-aws` gem version which was installed was `0.8.1` for me and it did not support the India region.
After upgrading the `fog-aws` gem to `0.9.4`, the ec2 resources were accessible for India region.
```
gem install fog-aws -v 0.9.4
```
