### ISSUE TITLE
Fog::Compute::AWS::Error: UnauthorizedOperation => You are not authorized to perform this operation

### ISSUE THREAD

**Issue by ofir-simplee** [chef/knife-ec2#423]
Hi,
I want to give my team leaders the ability to create new servers without bothering me and my team
I am trying to use "knife ec2 server create", with my admin user there is no problem!
but i created a restricted user named "chef" and i am trying to give him the right amount of access but it fails every time at the same place "Fog::Compute::AWS::Error: UnauthorizedOperation => You are not authorized to perform this operation"

even when i grant the user all resources  ("*")it fails. 

so i'm probably forgetting to add an action for this user
what am i missing

```
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeInstances",
                "ec2:DescribeImages",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeVpcs",
                "ec2:DescribeSubnets",
                "ec2:CreateTags",
                "ec2:DescribeSecurityGroups"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": "ec2:RunInstances",
            "Resource": [
                "arn:aws:ec2:us-east-1:bar:network-interface/**",
                "arn:aws:ec2:us-east-1:bar:volume/**",
                "arn:aws:ec2:us-east-1:bar:security-group/sg-foo",
                "arn:aws:ec2:us-east-1::image/ami-foo",
                "arn:aws:ec2:us-east-1:bar:subnet/subnet-foo",
                "arn:aws:ec2:us-east-1:bar:vpc/vpc-foo",
                "arn:aws:ec2:us-east-1:bar:instance/**"
            ]
        }
    ]
}
```

Thanks

**Comment by Aliasgar16** [comment]
@ofir-simplee this seems to be the permissions issue with the `ec2 IAM user` you have created and not related to `knife-ec2`. Adding some links below for your reference to help you identify the issue.

[ec2 Runinstances](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_RunInstances.html)
[granting required permissions for ec2 resources](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/ec2-api-permissions.html)
[IAM policies for ec2](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policies-for-amazon-ec2.html)
[access management in ec2](http://docs.aws.amazon.com/IAM/latest/UserGuide/access.html)
[IAM permissions](http://docs.aws.amazon.com/IAM/latest/UserGuide/access_permissions.html)
[example IAM policies](http://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_examples.html)
[ec2 ARN](http://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html)

Thanks

**Comment by btm** [comment]
If you need further help, please post a message in the 'chef' category on [Discourse](https://discourse.chef.io/) instead of filing an issue here.

https://discourse.chef.io/
