### ISSUE TITLE
Fog UnknownParameter errors when creating new server

### ISSUE THREAD

**Issue by cswilliams** [chef/knife-ec2#444]
Hi,

On the latest fog (fog v.1.38.0 and fog-aws v.0.11.0), I get errors when running the following command:
knife ec2 server create -r <my_roles> -N my_node -I <my_ami> --region us-west-1 -Z us-west-1b -f m1.large -G default  --aws-access-key-id XXXX --aws-secret-access-key XXXX
ERROR: Fog::Compute::AWS::Error: UnknownParameter => The parameter EbsOptimized is not recognized

I ended up removing the code in ec2_server_create.rb for setting "server_def[:ebs_optimized]" and that gets rid of the error. However, then another error appears:
ERROR: Fog::Compute::AWS::Error: UnknownParameter => The parameter VolumeType is not recognized

I then removed line 1075 of ec2_server_create.rb:                'Ebs.VolumeType' => config[:ebs_volume_type],

and then everything works and the server will create.

**Comment by btm** [comment]
@cswilliams have you tried fog-aws v0.12.0 that was released on 9/22?

Did this fail in any ChefDK release with the gems that we ship or is this your own gem bundle?

**Comment by dheerajd-msys** [comment]
@cswilliams Please try with latest fog-aws v0.12.0. I verified that command works well for ebs-backed AMI.
Also check for instance type if that is supported for ebs-backed AMIs.
In your command you are using `m1.large` which might not a compatible instance type for your AMI.
Ref : http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html
      : https://forums.aws.amazon.com/thread.jspa?messageID=369046

**Comment by cswilliams** [comment]
Yeah, I'm no longer seeing the issue on fog-aws v0.12.0. Closing this...
