### ISSUE TITLE
AWS config file not recognized

### ISSUE THREAD

**Issue by howdoicomputer** [chef/knife-ec2#447]
When I put in my configuration block for my credentials files like so:

```
knife[:aws_config_file] = File.join(ENV['HOME'], "/.aws/config")
knife[:aws_credentials_file] = File.join(ENV['HOME'], "/.aws/credentials")
knife[:aws_profile] = 'prod'
```

I get an error:

```
ERROR: You did not provide a valid 'AWS Access Key Id' value.
ERROR: You did not provide a valid 'AWS Secret Access Key' value.
```

When I put in my keys using the `:aws_*` key values, everything works as expected.

Note, my credentials and config files are correct and work perfectly fine with the aws cli. If I'm doing something wrong then I'm not sure what.

My credentials file looks like this:

```
[default]
aws_access_key_id = foobar
aws_secret_access_key = foobar

[stage]
aws_access_key_id = foobar
aws_secret_access_key = foobar

[prod]
aws_access_key_id = foobar
aws_secret_access_key = foobar
```

And my config file looks like this:

```
[profile default]
region = us-east-1

[profile prod]
region = us-east-1

[profile stage]
region = us-east-1 
```

**Comment by dheerajd-msys** [comment]
@howdoicomputer ,  replacing  the knife[:aws_credentials_file] parameter with knife[:aws_credential_file] will solve this issue.

**Comment by NimishaS** [comment]
@howdoicomputer , any updates on this?

**Comment by btm** [comment]
I'm going to close this as resolved by fixing the typo in specifying the credential file. As @dheerajd-msys indicated, the correct setting is `knife[:aws_credential_file]`.

Let us know if you're still having problems @howdoicomputer.
 
https://github.com/chef/knife-ec2#aws-credential-file
