### ISSUE TITLE
Change default for --ebs-volume-type from standard (magnetic) to gp2 (SSD)

### ISSUE THREAD

**Issue by rjhintz** [chef/knife-ec2#451]
Change [ec2_server_create.rb](https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_server_create.rb)

```rb
 option :ebs_volume_type,
        :long => "--ebs-volume-type TYPE",
        :description => "Standard or Provisioned (io1) IOPS or General Purpose (gp2)",
        :proc => Proc.new { |key| Chef::Config[:knife][:ebs_volume_type] = key },
        :default => "standard"
```

to:

```rb
 option :ebs_volume_type,
        :long => "--ebs-volume-type TYPE",
        :description => "Standard or Provisioned (io1) IOPS or General Purpose (gp2)",
        :proc => Proc.new { |key| Chef::Config[:knife][:ebs_volume_type] = key },
        :default => "gp2"
```

to align with current AWS recommendations.

**This is a disruptive change with cost implications**.

See also #450. I have to do the prerequisite admin to do a PR, but didn't want this and the other issue to get lost.

**Comment by dheerajd-msys** [comment]
@rjhintz Thanks for your comments. We will get it fixed soon.

**Comment by rjhintz** [comment]
Ok, thanks. I couldn't figure out how to do a PR because the method for becoming a contributor seems obsolete. See #452

**Comment by NimishaS** [comment]
Fixed in https://github.com/chef/knife-ec2/pull/464
