### ISSUE TITLE
Fog::Compute::AWS::Error: RequestLimitExceeded when using KNIFE EC2 CREATE

### ISSUE THREAD

**Issue by jerseyfoxcom** [chef/knife-ec2#453]
I'm getting a Fog::Compute::AWS::Error: RequestLimitExceeded error intermittently when attempting to EC2 is "Waiting for Windows Admin password to be available".

Usually works fine, but 1 in 10 times i'm getting this error and it's causing us some issues in our plan to use KNIFE EC2 for automated deployment.

**Comment by jerseyfoxcom** [comment]
Having researched this - it looks like the following is happening 

http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#api-request-rate

Is there a way to retry and perform an exponential back-off with Knife-EC2?

**Comment by dheerajd-msys** [comment]
@jerseyfoxcom, Since this is intermittent error, I am unable to reproduce this error. Could you please tell me which command you used and other parameters with the command?

**Comment by dheerajd-msys** [comment]
@jerseyfoxcom Hope comments added in https://github.com/chef/knife-ec2/issues/462 help you for the similar issue. 
Please feel free to reopen if you still face issue.

**Comment by jerseyfoxcom** [comment]
Just as an FYI - I've resolve this issue my end by making the following changes to the KNIFE-EC2 Gem and recompiling it.

This is all in EC2_server_create.rb

  def check_windows_password_available(server_id)
	sleep 10 #TODO:// Exponential backout required to prevent connection.get_password_data being called constantly.
	#Added this at the start of the loop as it doesn't fire if the return false is hit
    response = connection.get_password_data(server_id)
    if not response.body["passwordData"]
      return false
    end
    response.body["passwordData"]
  end
This method was firing 5 times a second for me, and moving the sleep to the top of the function rather than at the end (which wasn't being hit when a return false; was hit first) has sorted this problem out.

**Comment by jerseyfoxcom** [comment]
Just as an FYI - I've resolve this issue my end by making the following changes to the KNIFE-EC2 Gem and recompiling it.

This is all in EC2_server_create.rb

      def check_windows_password_available(server_id)
		sleep 10 #ALTIS - TODO:// Exponential backout required to prevent connection.get_password_data being called constantly.
		#Added this at the start of the loop as it doesn't fire if the return false is hit
        response = connection.get_password_data(server_id)
        if not response.body["passwordData"]
          return false
        end
        response.body["passwordData"]
      end

This method was firing 5 times a second for me, and moving the sleep to the top of the function rather than at the end (which wasn't being hit when a return false; was hit first) has sorted this problem out.

**Comment by NimishaS** [comment]
@jerseyfoxcom , this issue is resolved in knife-ec2 0.15.0.

**Comment by jerseyfoxcom** [comment]
Hey, that's brilliant - we've been using a forked version with this change for some time, but that will allows us to go back onto the main branch again.

Adam
