### ISSUE TITLE
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate knife-windos-1.7.0, because winrm-1.2.0 conflicts with winrm (~> 2.1) (Gem::ConflictError)

### ISSUE THREAD

**Issue by dilippanwar1** [chef/knife-ec2#454]
I installed the latest chef-dk and trying to create an instance using knife ec2 plugin.
I am getting an error mentioned below-
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2104:in `raise_if_conflicts': Unable to activate knife-windos-1.7.0, because winrm-1.2.0 conflicts with winrm (~> 2.1) (Gem::ConflictError)
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1316:in `block in activate_dependencies'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `each'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1302:in `activate_dependencies'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1284:in `activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
        from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from /home/ubuntu/.chefdk/gem/ruby/2.1.0/gems/knife-ec2-0.13.0/lib/chef/knife/ec2_server_create.rb:20:in `<top (required)>'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `load'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `block in load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `each'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife/core/subcommand_loader.rb:35:in `load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:126:in `load_commands'
        from /opt/chefdk/embedded/apps/chef/lib/chef/knife.rb:207:in `run'
        from /opt/chefdk/embedded/apps/chef/lib/chef/application/knife.rb:139:in `run'
        from /opt/chefdk/embedded/apps/chef/bin/knife:25:in `<top (required)>'
        from /opt/chefdk/bin/knife:40:in `load'
        from /opt/chefdk/bin/knife:40:in `<main>'
######################
Below is my cmd used to create instance
 knife ec2 server create -r 'role[foundation]' --ebs-size 8 -I ami-8688 -f t2.micro --node-nme bbc-app1.nodomanin.com --ssh-key AWSPersonal --subnet subnet-68969 -g sg-dce697a5 --ssh-user ubuntu -E dev --iam-profile bbc -i /home/ubuntu/.chef/AWSPersonal.pem --node-ssl-verify-mode none --tags owner=dilip,product=devops-test,client=bbc,Name=bbc-ap1 -j '{"set_fqdn":"bbc-app1.nodomanin.com"}'
#######################
As a temporary solution, I uninstalled the winrm -v 1.2.0 gem to make it working however, I have to automate this command and it is not working from that perspective.

**Comment by dheerajd-msys** [comment]
@dilippanwar1, I have got `knife ec2 server create` command working with `ChefDK 0.19.6` and `$ chef gem list | egrep 'knife|winrm'
knife-ec2 (0.13.0)
knife-push (1.0.1)
knife-spork (1.6.2)
knife-windows (1.7.0)
winrm (2.1.0)
winrm-elevated (1.0.1)
winrm-fs (1.0.0)
`
So it seems there may be multiple gem in your library which is causing the failure. Please try to use latest gems. 
Similar issue for your reference : https://github.com/chef/chef-provisioning/issues/370

**Comment by dheerajd-msys** [comment]
Closing this issue, feel free to reopen if you still get error.
Thanks.
