### ISSUE TITLE
Unable to create instance with Iam profile

### ISSUE THREAD

**Issue by dilippanwar1** [chef/knife-ec2#455]
I am getting below error-
ERROR: Fog::Compute::AWS::Error: UnauthorizedOperation => You are not authorized to perform this operation. Encoded authorization failure message: ixPqZPsDYfQYC1KcpwE_QRNlBXtOO3affAg1twm5dfdVQ57J7aT6Pia98GLguc6z5Cnh-fcnnC1D2TdRc0eHYWAgihNgj362WL7S2WN-7aDvG84kMWHQzsPQ7-4esy1dJOX5B5I91mJv_KNFEeWZR9G32oZ7acsI3dgx69zHejHNCSnvcMaAhBAD8lck1rcJ9Ct6Bsjhltfhrvs5QUs2Wv5z1mMTVj7uFkfALsuhYQsjy6GqjpOUIe46S9cMIvKmYpMs3zsjHDCV86NmZPrCocMumDOtTTaUQJPpJAdMFrd27Nnksc6Hww9_HyJbpFihs1C2ODVjQl9gVCDlWiwTR81s96HXnX97OxZE5X4afBo-_h7bn0Inn9Qv7nEAsLkLY_dHJzdERjA

I am passing profile as --iam-profile bbc

Please help

**Comment by dheerajd-msys** [comment]
@dilippanwar1, Please check if your `--iam-profile` is authorized for creating VM. You can check it from AWS console under IAM service for your profile. **AmazonEC2RoleforSSM** is policy which should be accessed from your profile.

**Comment by dheerajd-msys** [comment]
Closing this issue now, hope above comment help you. Please feel free to re-open if error still persists.
