### ISSUE TITLE
Unable to bootstrap windows instance after provisioning

### ISSUE THREAD

**Issue by sernapallyanurag** [chef/knife-ec2#456]
This is my command:

``
 knife ec2 server create -N windowstest -I ami-2843e54b -f t2.micro --bootstrap-protocol winrm --winrm-user .\windowsuser --winrm-password admin@123 --region ap-southeast-1 --availability-zone ap-southeast-1b --subnet subnet-0707est23  --winrm-transport plaintext --security-group-ids sg-5674abc --associate-public-ip
``

I have installed knife-windows gem
.
**SSH Target Address: ec2-xx-xx-xx-xx.ap-southeast-1.compute.amazonaws.com()** instead of **winRM**.

``
..ERROR: Failed to authenticate to ec2-xx-xx-xx-xx.ap-southeast-1.compute.amazonaws.com as .\windowsuser
Response: WinRM::WinRMAuthorizationError
Hint: Make sure to prefix domain usernames with the correct domain name.
Hint: Local user names should be prefixed with computer name or IP address.
EXAMPLE: my_domain\user_namer
``

Is there something I am missing?

**Comment by dheerajd-msys** [comment]
@sernapallyanurag, Please use `--winrm-transport ssl` and `--winrm-ssl-verify-mode verify_none` .
Also ensure that your `--security-group-ids`  has ports `5986,5985,3389` added.

**Comment by dheerajd-msys** [comment]
Hope aforementioned options help you. Closing this issue. 
Thanks.
