### ISSUE TITLE
Generate temporary keypair when none is supplied

### ISSUE THREAD

**Issue by sethrosenblum** [chef/knife-ec2#457]
The packer [Amazon AMI builder](https://www.packer.io/docs/builders/amazon-instance.html#ssh_keypair_name) will generate a temporary keypair when provisioning a host if no Key Pair name is specified.  This is nice for security purposes when you don't want a single key to have access to a large slew of machines, and when you only use that key for the provisioning process.

It would be nice if knife-ec2 also had this feature.

**Comment by dheerajd-msys** [comment]
Thanks @sethrosenblum pointing this out, We will work to add this feature.
