### ISSUE TITLE
knife-ec2 0.14.0 breaks compatibility with older chef-client

### ISSUE THREAD

**Issue by nicwaller** [chef/knife-ec2#461]
The latest version of knife-ec2 (0.14.0) introduces a [requirement for Ruby 2.2.2](https://github.com/chef/knife-ec2/commit/c0b420fc3728da1886e5d4560f6394b609006e45) or greater.

Chef [began bundling Ruby 2.3](https://discourse.chef.io/t/chef-12-14-will-be-on-ruby-2-3-1/9206) with version 12.14, released about 3 months ago. Versions of chef-client prior to 12.14 install an older version of Ruby (2.1.6p336) which does not satisfy the requirements for knife-ec2 0.14.0.

> What’s New in 12.14
> Upgraded Ruby version from 2.1.9 to 2.3.1 Adds several performance and functionality enhancements.
> https://docs.chef.io/release_notes.html

Therefore, knife-ec2 requires chef-client 12.14 or newer and this should be described in the CHANGELOG.

**Comment by dheerajd-msys** [comment]
@nicwaller I verified it from my end too that knife-ec2-0.14.0 requires chef-client 12.14.
So we will modify the CHANGELOG accordingly. Thanks for pointing this out.

**Comment by NimishaS** [comment]
Fixed with https://github.com/chef/knife-ec2/pull/467

**Comment by btm** [comment]
Added a post on discourse: https://discourse.chef.io/t/knife-ec2-0-14-0-released/9972/2
