### ISSUE TITLE
Using ec2 arn_role in AWS instead of access keys/STS

### ISSUE THREAD

**Issue by jefe78** [chef/knife-ec2#463]
I'm trying to use knife ec2, however, we have nested accounts and use arn_roles in our aws config. 

Config looks like this:
```
[default]
output=json
region=us-east-1

[profile companyname]
source_profile=default
role_arn=arn:aws:iam::CHOPPED
mfa_serial=arn:aws:iam::chopped/username
region=us-west-2
```

Is there a way to use the 'companyname' profile?

**Comment by dheerajd-msys** [comment]
@jefe78 I have investigated http://docs.aws.amazon.com/cli/latest/topic/config-vars.html but didn't get any lead for company name profile.
 Although there is possibility to create group and add users to the group and assign the policy. Please let me know if this help.

**Comment by NimishaS** [comment]
@jefe78 , seems like AWS itself doesn't have any policy to provide `companyname` profile. So this can't be supported. Closing this.
