### ISSUE TITLE
knife ec2 server create prompts for overwriting node even when --yes is used

### ISSUE THREAD

**Issue by cswilliams** [chef/knife-ec2#469]
During a validatorless bootstrap, knife ec2 server create will prompt the user “Node XXX exists, overwrite it? (Y/N)” if the node already exists.  Passing the --yes option should confirm this prompt automatically, but it does not.

Fixed in #458

**Comment by dheerajd-msys** [comment]
@cswilliams, Thank you for pointing this issue and contribution to resolve. I have verified it on my end.

**Comment by NimishaS** [comment]
Fixed in https://github.com/chef/knife-ec2/pull/458
