### ISSUE TITLE
Windows user add hangs forever if password is greater than 14 characters

### ISSUE THREAD

**Issue by irvingpop** [chef/knife-ec2#470]
This bit of code: https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_server_create.rb#L962 will result in a y/n prompt if the password is greater than 14 characters, due to a warning about older Windows not being able to deal with older passwords.

The simple solution is to add a `/yes` flag.

Some user-data scripts, such as the one used by our field teams, also disable password complexity requirements in order to minimize the number of surprises encountered when supplying a password:  https://gist.github.com/vinyar/6735863

**Comment by dheerajd-msys** [comment]
@irvingpop, we tried to manually run `net user /add` command on Windows 2012, 2008 and 2003. It ran successfully without any message prompt. Can you please share which version of windows were you using?

**Comment by irvingpop** [comment]
This is what I get on stock Windows 2012R2 (launched from the default EC2 AMI):

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:>net user /add bob TooLongPassword
The password entered is longer than 14 characters.  Computers
with Windows prior to Windows 2000 will not be able to use
this account. Do you want to continue this operation? (Y/N) [Y]:
```

**Comment by dheerajd-msys** [comment]
Windows has a password policy, where it prompts the user based on password complexity, password length and history. In our case, it is prompting since password exceeds the limit of 14 characters. This is to enable using the user accounts on Windows versions older than Windows 2000, since they don't support long passwords.
Adding /yes to the `net user /add` command in the code will override the necessary password policy requirements, like password length, set on all the servers.
We are looking at a solution to display these errors, and an ideal way to handle them.

**Comment by NimishaS** [comment]
@btm , we searched but didn't find any way to capture failure of `user-data` script.
There are 2 ways to handle this. None of them are perfect:
a) Check the password length initially when the user runs `knife azure server create -x <user> -P <Password>` command. If the length is greater than 14, we can prompt the user: `The password length is greater than 14 characters and it's not in compliance with the Windows password policy. Would you like to override it?`
If user says yes, we pass `/yes` along with `net user /add` command. If he says no, we exit with a message to provide password with a smaller length.
**Note**: This approach is not very suitable if someone wants to use `knife ec2 server create` command in automated scripts.

b) If the bootstrap doesn't happen after a particular time, we can show all the possible reasons of failure. One of them will include possible failure of `user-data` script and the path to check the user-data logs.

**Comment by NimishaS** [comment]
Fixed in https://github.com/chef/knife-ec2/pull/489.
