### ISSUE TITLE
creating multiple windows servers causes aws api request limit to be hit and failed bootstrap

### ISSUE THREAD

**Issue by Stromweld** [chef/knife-ec2#479]
When Knifing multiple windows servers and knife-ec2 gets to the point of waiting on windows password we have issues with hitting api rate limits and servers don't get bootstrapped. This typically happens after 2 servers are at the waiting for windows password. The 3rd or 4th server will then hit the error and knife command will stop.

Wondering if there is a way to throttle it so not so many requests are happening so frequently at that step or for knife-ec2 to ignore the error and keep trying till request doesn't fail?

**Comment by dheerajd-msys** [comment]
@Stromweld , I tried creating 4 windows servers simultaneously with `knife ec2 server create` command. But did not get API request limit issue. All servers are getting created and bootstrapped. 

Could you please share how did you create the servers and command used?

**Comment by Stromweld** [comment]
knife ec2 server create -r role[base-linux] -I ami-81e059e1 --subnet subnet-79ef460e --region us-west-2 -g sg-3926af5c -x administrator --node-name TAW2AM-TEST01 --environment base-linux-dev --flavor c4.large --iam-profile nativex_ec2  --ebs-optimized

Few things to note. I run this command from my Mac in our office not a workstation in AWS. This will knife a new server into one of our subnets inside our VPC using a custom windows AMI that we created based on the AWS Windows Server 2012 R2 AMI and we patch it each month and made sure winrm, firewall, random admin password, etc... are setup for knifing windows.

We actually use this script that I created to generate the knife commands and execute them in separate terminals. <script src="https://gist.github.com/Stromweld/66e8b705af1abbf6f0f715cd72eab7d5.js"></script>
We also use aliases for knife command that specify different configs for different organizations so if you try the script you take the default knife command and it'll use your default knife.rb file. The administrator.pem part is the AWS administrator key used to login to linux instances or to decrypt the windows password.

**Comment by dheerajd-msys** [comment]
@Stromweld, AWS works on `eventual consistency model` explained at http://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html#eventual-consistency. So in each retry request, it waits for its previous request's response to be available otherwise fails. So we need to keep `sleep` between each request.

Since you use your own script to create the servers, you can call `sleep` here https://gist.github.com/Stromweld/66e8b705af1abbf6f0f715cd72eab7d5#file-knife-helper-rb-L108 Or implement `exponential back-off algorithm` as explained here: http://docs.aws.amazon.com/general/latest/gr/api-retries.html.
`exponential back-off algorithm` means increasing the sleep interval between each retry request. This way you will have the response available for your following requests.

**Comment by Stromweld** [comment]
That script I built usese the AWS SDK simply for querying AWS for information to build the knife command. It then builds another ruby script and executes that in a new terminal windows on mac. The new script runs the knife command to knife a new EC2 instance and waits for it to succeed. If it fails the method you highlighted simply gets and decrypts the windows admin password (borrowed the code from the knife-ec2 project) and builds a knife bootstrap command since we have a server that was created in EC2 now but that has not been bootstrapped. I added the secondary script to catch the bootstrap errors with windows since we have run into it so many times. 

The primary script allows you to designate the number of servers you want to knife and it'll increment the hostname last 2 digit number and have you select an Subnet for each server you're looking to knife. Then it loops through and builds a knife command for each one and adds it to the secondary script to be executed in it's own terminal. So if I run the script and designate 4 servers I'll get 4 new terminal windows running a knife command that looks like this: 

knife ec2 server create -r role[base-linux] -I ami-81e059e1 --subnet subnet-79ef460e --region us-west-2 -g sg-3926af5c -x administrator --node-name TAW2AM-TEST01 --environment base-linux-dev --flavor c4.large --iam-profile nativex_ec2 --ebs-optimized

It's at this stage when the knife command is running and they get to the waiting for windows admin password to become available the knife command keeps pinging AWS to try and retrieve the password and it takes upwards of 4-6 minutes for AWS to make the windows admin password available. When all 4 hit this stage after a minute or so 1 or 2 of them will get an error from AWS saying request limit exceeded and knife command exits without bootstrapping the server.

**Comment by Stromweld** [comment]
I can also replicate the issue with 4 terminals and running the knife command all at the same time and not using my script. Please see the screenshot file. 
![screen shot 2017-02-06 at 9 15 11 am](https://cloud.githubusercontent.com/assets/3476391/22652705/160671f0-ec4d-11e6-9ec2-8c743f53b715.png)

Here is the terminal out put of one of the failed knife commands:

Last login: Mon Feb  6 09:07:11 on ttys001
Ignoring gherkin-2.12.2 because its extensions are not built.  Try: gem pristine gherkin --version 2.12.2
OSHOLA-019602:~ corey.hemminger$ knife ec2 server create -r role[base-linux] -I ami-81e059e1 --subnet subnet-79ef460e --region us-west-2 -g sg-3926af5c -x administrator --node-name TAW2AM-TEST03 --environment base-linux-dev --flavor c4.large --iam-profile nativex_ec2 --ebs-optimized
Ignoring gherkin-2.12.2 because its extensions are not built.  Try: gem pristine gherkin --version 2.12.2
Instance ID: i-03c7cea0f142cddfb
Flavor: c4.large
Image: ami-81e059e1
Region: us-west-2
Availability Zone: us-west-2a
Security Group Ids: sg-3926af5c
IAM Profile: nativex_ec2
Tags: Name: TAW2AM-TEST03
SSH Key: administrator

Waiting for EC2 to create the instance.....
Subnet ID: subnet-79ef460e
Tenancy: default
Private IP Address: 172.21.16.211

Waiting for winrm access to become available
SSH Target Address: 172.21.16.211(private_ip_address)
.
SSH Target Address: 172.21.16.211()
.
SSH Target Address: 172.21.16.211()
.
SSH Target Address: 172.21.16.211()
done

SSH Target Address: 172.21.16.211()

Waiting for Windows Admin password to be available..................................................................ERROR: Fog::Compute::AWS::Error: RequestLimitExceeded => Request limit exceeded.
OSHOLA-019602:~ corey.hemminger$

**Comment by dheerajd-msys** [comment]
Could you please try without `-r role[base-linux]` and `--environment base-linux-dev` ? I was wondering if there are any recipe which is making difference for windows server.

Also for creating windows server through knife ec2 you may use `--ssh-key somekey --winrm-transport ssl --winrm-ssl-verify-mode verify_none -g <security-group-id>`. Please make sure that your `--security-group-ids has ports 5986,5985,3389` added.

Sample command would be like :
`knife ec2 server create --node-name win2k12 -I ami-df8767bf -f t2.micro -x .\<username> -P "<password>" --ssh-key somekey --winrm-transport ssl --winrm-ssl-verify-mode verify_none --security-group-ids <security-groupId>`

**Comment by Stromweld** [comment]
From my screen shot you can see that the 2 failed machines never got the windows administrator password to decrypt it and login to start the bootstrapping of chef-client. The other 2 that didn't get the error continued to work correctly and had I taken a screenshot later you'd see them get the password, connect to winrm and start bootstrapping the chef-client onto the server. 

I can try your suggestion but don't think it's going to make a difference since the request limit is hit before it connects to the server.

**Comment by NimishaS** [comment]
@Stromweld , this kind of issue was raised previously too. Please check the comment here: https://github.com/chef/knife-ec2/issues/453#issuecomment-265682013

I would suggest you to add sleep before calling `get_password_data` method in your script(https://gist.github.com/Stromweld/66e8b705af1abbf6f0f715cd72eab7d5#file-knife-helper-rb-L108) as suggested by @dheerajd-msys . I observed that there is `knife ec2 server create` command also being called in the script(https://gist.github.com/Stromweld/66e8b705af1abbf6f0f715cd72eab7d5#file-knife-helper-rb-L87), which calls `get_password_data` internally.. Hence `get_password_data` actually gets called twice.

We'll also be adding sleep at the required place in `knife-ec2`.

**Comment by Stromweld** [comment]
I will add that, But adding the sleep to the official knife-ec2 gem is what will fix my issue for me. My call to the get_password_data is only used after a try of "knife ec2 create server" fails my script then builds a "knife bootstrap windows winrm" command for you and gets the password automatically from AWS. It's assuming the the failed knife command was able to create the ec2 instance but failed to connect and bootstrap chef client. This happens to us randomly so I added that to the script so we didn't have to manually gather the info for the bootstrap command. By the time knife ec2 server create fails the windows password is there and it had moved on to trying to connect. 

When trying to knife more than 2 servers and we get the FOG error just like in the other comment you referenced above and my try catch doesn't seem to catch that exit code as an error and the get_password_data doesn't get called.

**Comment by Stromweld** [comment]
My issue is essentially the exact same thing as #453

**Comment by NimishaS** [comment]
@Stromweld , https://github.com/chef/knife-ec2/pull/484 should fix your issue.

**Comment by NimishaS** [comment]
Can you please try with `knife-ec2` master branch now? You need to follow the given steps:
1. `gem uninstall knife-ec2` - This uninstalls the current installed version
2. `git clone https://github.com/chef/knife-ec2`
3. `cd knife-ec2`
4. `gem build knife-ec2.gemspec`
5. `gem install knife-ec2-0.13.0.gem`

Try running the `knife ec2 server create` commands after this. Hopefully this resolves your issue. Otherwise we'll consider increasing the sleep time.

**Comment by Stromweld** [comment]
@NimishaS I just tried out the new gem as outlined in your comment above and it worked great. I was able to knife 4 servers at the same time. They all completed as expected.

**Comment by NimishaS** [comment]
@Stromweld , this issue is resolved in `knife-ec2 0.15.0`.

**Comment by Stromweld** [comment]
Sweet thanks
