### ISSUE TITLE
Bootstrap Windows (2012 R2 and above platform) instance without user-data Not working for Windows AWS EC@2

### ISSUE THREAD

**Issue by oliyavan** [chef/knife-ec2#499]
Hi,
This the command I am using to spin windows2012 R2 without user data as per the doc, after launched the instance, it is waiting to bootstrap via winrm using port 5986.
`knife ec2 server create -N windowstest -I ami-e659c7f0 -f t2.micro --bootstrap-protocol winrm --winrm-user .\windowsuser --winrm-password admin@123 --winrm-transport ssl --winrm-ssl-verify-mode verify_none --winrm-transport plaintext --bootstrap-protocol winrm --security-group-ids sg-3f80ba40 --ssh-key Office-windows -VVV`
But it keeps on waiting but no response and I check the Security group also all ports are opened.
1. what is the possibility of failure and what is the solution?

**Comment by NimishaS** [comment]
@oliyavan , please try without passing `--winrm-transport plaintext --bootstrap-protocol winrm` options. For SSL transport, we can't give plaintext. `--bootstrap-protocol` will be set by default I guess.

Please check and let me know your findings.

**Comment by oliyavan** [comment]
@NimishaS i also tried without `--winrm-transport plaintext --bootstrap-protocol winrm` but still same the same, please check the below message.
`
Waiting for EC2 to create the instance.....
Public DNS Name: ec2-34-205-50-40.compute-1.amazonaws.com
Public IP Address: 34.205.50.40
Private DNS Name: ip-172-31-73-66.ec2.internal
Private IP Address: 172.31.73.66

Waiting for winrm access to become available
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com(dns_name)


.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
SSH Target Address: ec2-34-205-50-40.compute-1.amazonaws.com()
.
`
After this keep on waiting

**Comment by NAshwini** [comment]
Hi @oliyavan ,

**Comment by NAshwini** [comment]
Hi @oliyavan ,
I tried with this command & for me it is working successfully "knife ec2 server create --node-name AshWin4 -I ami-11e84107 -f t2.micro -x '.\Ashwini' -P "ec2user@123" --winrm-transport ssl --winrm-ssl-verify-mode verify_none --node-ssl-verify-mode none -VV"

**Comment by NAshwini** [comment]
@oliyavan , any updates on this?

**Comment by NimishaS** [comment]
@oliyavan , closing this issue as @NAshwini could run the command successfully.

Please feel free to reopen is you still face difficulty.
