### ISSUE TITLE
Chef Client fails to download when running `knife ec2 server create`

### ISSUE THREAD

**Issue by scarolan** [chef/knife-ec2#500]
The command I ran:

knife ec2 server create -x Administrator --node-name WindowsTest2 --identity-file C:\Users\chef\.ssh\id_rsa --ssh-key chef_demo_2x --region us-west-2 -g sg-aff696d4 --subnet subnet-31f9016a -I ami-2ad04f4a --flavor m3.medium --tags Name="WindowsTest2" --run-list recipe['chef-client::task'],recipe['fourthcoffee']

The error message output:
```
172.31.54.57 Attempting to download client package using PowerShell if available...
172.31.54.57 powershell.exe -ExecutionPolicy Unrestricted -InputFormat None -NoProfile -NonInteractive -File  C:\chef\wget.ps1 "https://www.chef.io/chef/download?p=windows&pv=2012&m=x86_64&DownloadContext=PowerShell&v=12" "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
172.31.54.57 Exception calling "DownloadFile" with "2" argument(s): "Unable to connect to
172.31.54.57 the remote server"
172.31.54.57 At C:\chef\wget.ps1:14 char:1
172.31.54.57 + $webClient.DownloadFile($remoteUrl, $localPath);
172.31.54.57 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
172.31.54.57     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
172.31.54.57     + FullyQualifiedErrorId : WebException
172.31.54.57
172.31.54.57 Failed download: download completed, but downloaded file not found
172.31.54.57 Warning: Failed to download "https://www.chef.io/chef/download?p=windows&pv=2012&m=x86_64&DownloadContext=PowerShell&v=12" to "C:\Users\ADMINI~1\AppData\Local\Temp\chef-client-latest.msi"
172.31.54.57 Warning: Retrying download with cscript ...
172.31.54.57 C:\chef\wget.vbs(47, 1) msxml3.dll: The operation timed out
172.31.54.57
172.31.54.57
172.31.54.57 Failed download: download completed, but downloaded file not found
172.31.54.57 Exiting without bootstrapping due to download failure.
ERROR: Failed to execute command on 172.31.54.57 return code 1
ERROR: Bootstrap command returned 1
```

**Comment by scarolan** [comment]
This was resolved by adding `--associate-public-ip` to the command.  We might want to mention that in the README to warn future users.

**Comment by btm** [comment]
@scarolan I'm not sure what your environment is such that you needed `--associate-public-ip`. From the logs, it looks like your node had a private address and you were able to connect to it (`172.31.54.57`), but it did not have internet access. Adding a public IP could provide that, but adding an internet gateway to the VPC would have worked too. 

Maybe we could add an error message like "Verify that you have public internet access from this node" when we fail to download. The "download completed" portion of the existing message is a bit confusing.
