### ISSUE TITLE
Knife ec2 - Bootstrap fails with an error /etc/chef/client.pem is not present

### ISSUE THREAD

**Issue by sasydharan** [chef/knife-ec2#504]
knife ec2 server create -I ami-c58c1dd3 -f t2.micro --region us-east-1 -z us-east-1a -N node1 --subnet subnet-3422fc18 --ssh-user ec2-user -i ~/.ssh/name.pem --ssh-key name --use-sudo-password name.pem -x ec2-user

output of the command always fails with the below error. Manual bootstrap of the spinning instance works only with the option of knife bootstrap .... --sudo and the same(--sudo) cannot be used in knife ec2 server create as its missing in the option. 

Error : - 
ec2-54-84-46-200.compute-1.amazonaws.com Starting the first Chef Client run...
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:18:58+00:00] INFO: Forking chef instance to converge...
ec2-54-84-46-200.compute-1.amazonaws.com Starting Chef Client, version 12.20.3
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:18:59+00:00] INFO: *** Chef 12.20.3 ***
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:18:59+00:00] INFO: Platform: x86_64-linux
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:18:59+00:00] INFO: Chef-client pid: 2811
ec2-54-84-46-200.compute-1.amazonaws.com Creating a new client identity for temp1 using the validator key.
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:19:00+00:00] INFO: Client key /etc/chef/client.pem is not present - registering
ec2-54-84-46-200.compute-1.amazonaws.com
ec2-54-84-46-200.compute-1.amazonaws.com ================================================================================
ec2-54-84-46-200.compute-1.amazonaws.com Chef encountered an error attempting to create the client "temp1"
ec2-54-84-46-200.compute-1.amazonaws.com ================================================================================
ec2-54-84-46-200.compute-1.amazonaws.com
ec2-54-84-46-200.compute-1.amazonaws.com Platform:
ec2-54-84-46-200.compute-1.amazonaws.com ---------
ec2-54-84-46-200.compute-1.amazonaws.com x86_64-linux
ec2-54-84-46-200.compute-1.amazonaws.com
ec2-54-84-46-200.compute-1.amazonaws.com
ec2-54-84-46-200.compute-1.amazonaws.com Running handlers:
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:19:00+00:00] ERROR: Running exception handlers
ec2-54-84-46-200.compute-1.amazonaws.com Running handlers complete
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:19:00+00:00] ERROR: Exception handlers complete
ec2-54-84-46-200.compute-1.amazonaws.com Chef Client failed. 0 resources updated in 01 seconds
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:19:00+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:19:00+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:19:00+00:00] ERROR: No socketless chef-zero server on given port 8889
ec2-54-84-46-200.compute-1.amazonaws.com [2017-06-12T19:19:00+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by NAshwini** [comment]
Hi @sasydharan,

I found that you are passing user name & password twice.
i.e "knife ec2 server create -I ami-c58c1dd3 -f t2.micro --region us-east-1 -z us-east-1a -N node1 --subnet subnet-3422fc18 **--ssh-user ec2-user-i ~/.ssh/name.pem --ssh-key name --use-sudo-password name.pem -x ec2-user**"

I tried with this command & for me it is working successfully `knife ec2 server create -N AshTestRHEL7 -I ami-b63769a1 -f t2.micro --ssh-key Ash1 -i C:\Users\MSys\.ssh\Ash1.pem --ssh-user ec2-user --subnet subnet-27377942 --region us-east-1 -Z us-east-1d -r 'recipe[cbk1::default]`

**Comment by sasydharan** [comment]
Hi @NAshwini ,
Thank you for figuring it out. I was about to embed some sudo commands on user-data file but now i got the issue. Thanks for the command it works like charm.
