### ISSUE TITLE
Allow Chef tags to be different from AWS tags

### ISSUE THREAD

**Issue by rlaveycal** [chef/knife-ec2#509]
The current master branch allows:
- tags to be applied to the AWS instance
- tags to be applied to the AWS root volume
- instance tags to be optionally applied to the Chef node (0.15.0 always does it).

My problem is that I want to apply a tag to the Chef node that **isn't** in the form `key=value` i.e. I want to apply the tag `mytag`. Attempting to do this fails at present with the error `ERROR: Tags should be entered in a key = value pair`

It would be useful to have a `--chef-tags` option that didn't enforce the key=value syntax.

The command semantics would then be:
- Chef tags are not set by default (current behaviour)
- if `--tag-node-in-chef` is set then Chef is tagged
  - if `--chef-tags` is set then they are used
  - else `--tags` are used

**Comment by Vasu1105** [comment]
Need to add option  `--tags TAGS   Comma separated list of tags to apply to the node ` which is available in knife bootstrap command.

**Comment by rlaveycal** [comment]
Given that multiple `--security-group-id` instances now replace the `--security-group-ids` option maybe tags should follow the same pattern? Could then have `--aws-tag` and `--chef-tag` options
