### ISSUE TITLE
Add support for launching a T2 instance as Unlimited

### ISSUE THREAD

**Issue by jritchey** [chef/knife-ec2#519]
It would be nice if knife ec2 create supported the --credit-specification. To add T2 unlimited support to an instance on creation. 

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/t2-unlimited.html#launch-t2

# Environment: AWS

# Expected Result:
Support for the --credit-specification CpuCredits=unlimited

**Comment by jackl0phty** [comment]
+1 for this feature.

**Comment by dheerajd-msys** [comment]
Thanks @jritchey for pointing this out. We will keep it in our basket and work on it.

**Comment by tas50** [comment]
Released in 1.0.11
