### ISSUE TITLE
Boostrap fails when using --winrm-transport ssl --winrm-ssl-verify-mode verify_none

### ISSUE THREAD

**Issue by nick2585** [chef/knife-ec2#521]
Version: knife-ec2 (0.17.0)

Environment: I am running MacOS and attempting to Bootstrap an Amazon node with chef on Windows over SSL. If I change the below command to --winrm-transport plaintext, everything works.

Scenario:

knife ec2 server create --node-name excel-dev-ssl --ebs-size 128 --flavor t2.micro --region us-east-1 --subnet subnet-xxxxxx --image ami-ac8156d1 --security-group-id sg-xxxxxx --security-group-id sg-xxxxxxxx --security-group-id sg-xxxxxx -x 'Administrator' --ssh-key aws-key  key --user-data bootstrapwinchefnodeamazon3.ps1 --winrm-transport ssl --winrm-ssl-verify-mode verify_none –p 5986 -VV

user-data file:
<powershell>
winrm quickconfig -q
winrm create winrm/config/Listener?Address=*+Transport=HTTP
winrm set winrm/config/winrs '@{MaxMemoryPerShellMB="300"}'
winrm set winrm/config '@{MaxTimeoutms="1800000"}'
winrm set winrm/config/service '@{AllowUnencrypted="true"}'
winrm set winrm/config/service/auth '@{Basic="true"}'
netsh advfirewall firewall add rule name="WinRM 5985" protocol=TCP dir=in localport=5985 action=allow
netsh advfirewall firewall add rule name="WinRM 5986" protocol=TCP dir=in localport=5986 action=allow
NetSh Advfirewall set allprofiles state off
net stop winrm
sc.exe config winrm start=auto
net start winrm
</powershell>

Output:
Waiting for winrm access to become availableDEBUG: Looking for key subnet_id and found value subnet-xxxxxx
DEBUG: Looking for key region and found value us-east-1
DEBUG: Looking for key use_iam_profile and found value false
DEBUG: Looking for key aws_access_key_id and found value
DEBUG: Looking for key aws_secret_access_key and found value
DEBUG: Looking for key aws_session_token and found value 

SSH Target Address: 10.33.10.191(private_ip_address)
DEBUG: Looking for key winrm_port and found value 5986
.
SSH Target Address: 10.33.10.191()
DEBUG: Looking for key winrm_port and found value 5986
.
SSH Target Address: 10.33.10.191()
DEBUG: Looking for key winrm_port and found value 5986
.
SSH Target Address: 10.33.10.191()
DEBUG: Looking for key winrm_port and found value 5986
.
SSH Target Address: 10.33.10.191()
DEBUG: Looking for key winrm_port and found value 5986
.
SSH Target Address: 10.33.10.191()
DEBUG: Looking for key winrm_port and found value 5986

Any help would be greatly appecaited. Thanks!

**Comment by dheerajd-msys** [comment]
@nick2585 Could you please try running your command with non-Admin user and password i.e. `-x  .\dheeraj  -P "xxxxxxxxx"` along with other option?

Also please make sure if your security groups have added inbound rule for ports 5985 & 5986.

I have tried with these options and it worked for me. Simultaneously we need to look into error for user `Administrator`

**Comment by dheerajd-msys** [comment]
@nick2585 It seems from your console log that you are hitting into private ip address for ssh. This is the case when you are into VPC. Try to add `--associate-public-ip`  for your command with `Administrator` user. 
and let me know if it works.

**Comment by Vasu1105** [comment]
@nick2585 any updates on this.
