### ISSUE TITLE
Convert this gem to use the aws-sdk instead of fog

### ISSUE THREAD

**Issue by tas50** [chef/knife-ec2#529]
We shouldn't be using fog for knife-ec2 when there's an official aws SDK for ruby. The SDK is continuously updated and bring in the latest support for new regions and other functionality. Additionally we have to bundle several fog gems in ChefDK since we rely on fog here. We should convert this gem to use the aws-sdk (v2 for now).

**Comment by vsingh-msys** [comment]
Addressed in https://github.com/chef/knife-ec2/pull/587
