### ISSUE TITLE
Chef-15: Window node bootstrapping

### ISSUE THREAD

**Issue by vsingh-msys** [chef/knife-ec2#576]
### Describe the Enhancement:
As bootstrapping of node logic now moved from knife-windows v3 to chef infra 15. In order to support this currently no need of knife-windows plugin in knife-ec2.

**Comment by btm** [comment]
Fixed by #578

**Comment by btm** [comment]
the requirement is dropped, in #578, but there's work to do to make the windows portions of the code work again.

**Comment by btm** [comment]
Fixed in #584.
