### ISSUE TITLE
Rename Ec2Base#connection to Ec2Base#ec2_connection

### ISSUE THREAD

**Issue by vsingh-msys** [chef/knife-ec2#582]
### Describe the Enhancement:

There is a conflict of `connection` method while we inheriting the class `Chef::Knife::Bootstrap` class into `Ec2ServerCreate`  both having `connection` method one for aws connection came from module `Ec2Base` another for bootstrap node connection from the train.
``
### Describe the Need:

Now we are going to change design implementation so both connection methods are required.
For now, I can only think of renaming `Ec2Base` module connection method to `ec2_connection`

**Comment by dheerajd-msys** [comment]
Closing as it merged in https://github.com/chef/knife-ec2/pull/583
