### ISSUE TITLE
ERROR: Each network interface requires a device index.

### ISSUE THREAD

**Issue by pg1671** [chef/knife-ec2#601]
I am creating server instances using knife-ec2 and the script I have been using for years has been failing since I have installed the latest versions of knife-ec2 (probably after the 1.0) release. 
My latest error is:
ERROR: Each network interface requires a device index.

I am using the CLI.

Command is:
knife ec2 server create -r role[default] -I {ami} -f t3.large -S ec2-us-west-2 -i {pem_file} -U {username} --region us-west-2 -Z us-west-2a -N default --ebs-size 30 --associate-eip {ip} --subnet {subnet} --server-connect-attribute public_ip_address --security-group-id {security_group}

**Comment by vsingh-msys** [comment]
Fixed in #602
