### ISSUE TITLE
I can't bootstrap an ec2 AWS instance

### ISSUE THREAD

**Issue by mviscencio** [chef/knife-ec2#619]
# Version: 

Chef Infra Client: 15.4.45

# Environment:
Ubuntu 18.04 aws-cli/1.16.266 Python/3.5.2 Linux/5.0.0-36-generic botocore/1.13.2
knife.rb:
{code}
current_dir = File.dirname(__FILE__)
log_level :info
log_location STDOUT
node_name "mviscencio"
client_key "#{current_dir}/mviscencio_promad.pem"
cookbook_path ["~/repos/cookbooks/"]
chef_server_url "https://chef-server.internal.org/organizations/org"
validation_client_name "chef-validator"
knife[:aws_access_key_id] = "***********************"
knife[:aws_secret_access_key] = "**************************"
knife[:editor] = "vim"
trusted_certs_dir        "#{current_dir}/trusted_certs"
ssl_verify_mode :verify_none

# Scenario:

I am trying to create a new Ec2 instance using knife ec2 server create , but I am facing the following error:
{code}
mviscencio@ubuntu ~ ORG server create -r "role[some-role]" -I ami-000db10762d0c4c05 -N "Some-Role" -S Keypar -f t2.medium -U ec2-user --sudo -i ~/.ssh/Keypar.pem --region us-east-1   -g sg-*********** --subnet subnet-****** --ebs-size 500 –node-ssl-verify-mode none -VV
INFO: Using configuration from /home/mviscencio/.chef/knife.rb
DEBUG: Checking if we need to accept Chef license to bootstrap node
DEBUG: Reading products and relationships...
DEBUG: Successfully read products and relationships
DEBUG: License acceptance required for chef version: 15
DEBUG: Searching for the following licenses: ["infra-client", "inspec"]
DEBUG: Found license chef_infra_client at /home/mviscencio/.chef/accepted_licenses/chef_infra_client
DEBUG: Found license inspec at /home/mviscencio/.chef/accepted_licenses/inspec
DEBUG: Missing licenses remaining: []
DEBUG: All licenses present
DEBUG: Using AWS region us-east-1
DEBUG: Setting up AWS connection using aws_access_key_id AK******************* aws_secret_access_key: *************************************** aws_session_token: 

Waiting for EC2 to create the instance
Instance ID: i-0b0ba758f084c60e2
Flavor: t2.medium
Image: ami-000db10762d0c4c05
Region: us-east-1
Availability Zone: us-east-1f
Security Group Ids: sg-************
AWS Tags: Name: Some-Role
SSH Key: OpenSystems
T2/T3 Unlimited: Disabled

Subnet ID: subnet-*******************
Tenancy: default
Private IP Address: 10.0.0.165

Waiting for sshd access to become available
SSH Target Address: 10.0.0.165(private_ip_address)
DEBUG: No ssh gateway found, making a direct connection
DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: ssh failed to connect: 10.0.0.165
.DEBUG: sshd accepting connections on 10.0.0.165, banner is SSH-2.0-OpenSSH_7.4

done

SSH Target Address: 10.0.0.165(private_ip_address)
Connecting to 
Traceback (most recent call last):
        17: from /usr/bin/knife:350:in `<main>'
        16: from /usr/bin/knife:350:in `load'
        15: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/bin/knife:24:in `<top (required)>'
        14: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/application/knife.rb:162:in `run'
        13: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife.rb:228:in `run'
        12: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife.rb:484:in `run_with_pretty_exceptions'
        11: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/local_mode.rb:42:in `with_server_connectivity'
        10: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife.rb:485:in `block in run_with_pretty_exceptions'
         9: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife/bootstrap.rb:569:in `run'
         8: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife/bootstrap.rb:620:in `connect!'
         7: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife/bootstrap.rb:692:in `do_connect'
         6: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife/bootstrap/train_connector.rb:70:in `connect!'
         5: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.4.45/lib/chef/knife/bootstrap/train_connector.rb:57:in `connection'
         4: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh.rb:76:in `connection'
         3: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/transports/ssh.rb:89:in `validate_options'
         2: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/options.rb:71:in `validate_options'
         1: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/options.rb:71:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/train-core-3.1.4/lib/train/options.rb:73:in `block in validate_options': You must provide a value for "host". (Train::ClientError)
{code}

# Steps to Reproduce:

[If you are filing an issue what are the things we need to do in order to repro your problem?]

# Expected Result:

[What are you expecting to happen as the consequence of above reproduction steps?]

# Actual Result:

[What actually happens after the reproduction steps?]

**Comment by dheerajd-msys** [comment]
Hi @mviscencio From your command it looks like it is missing `--associate-public-ip` flag.
Please try to run your command adding this attribute and let us know if there is an issue.

Thank you!

**Comment by mviscencio** [comment]
Hello, @dheerajd-msys  *--associate-public-ip* that's worked smoothly, thank you very much, however, there is a way to not use an EIP on each instance launch? 
Best Regards

**Comment by dheerajd-msys** [comment]
Ok Great!! Yeah when you create and bootstrap any machine under VPC, It requires to be attached with Public IP.

Closing this issue as it's resolved.
