### ISSUE TITLE
Train SSH Connection Error

### ISSUE THREAD

**Issue by saadnaveed** [chef/knife-ec2#633]
# Version: 1.0.21

[Version of the project installed]

# Environment: Mac OS X

[Details about the environment such as the Operating System, cookbook details, etc...]

# Scenario: Trying to use `knife ec2 server create` to deploy a new instance and run chef on it.

[What you are trying to achieve and you can't?]

# Steps to Reproduce:

1.) Run `knife ec2 server create`

Currently, if `server.public_dns_name` returns a blank string `""`, then we'll still use that to connect as the host, which results in the following error:

    ```
    Connecting to
    ERROR: Train::ClientError: You must provide a value for "host".
    ```

The issue is here: https://github.com/chef/knife-ec2/blob/master/lib/chef/knife/ec2_server_create.rb#L1414

The fix is to make sure to check for an empty string on both public and private attributes.

A potential fix is to replace this method `server_name` with the following: 

```
def server_name
        return nil unless server

        if server.public_dns_name && !server.public_dns_name.empty?
          server.public_dns_name
        elsif server.private_dns_name && !server.private_dns_name.empty?
          server.private_dns_name
        else
          server.private_ip_address
        end
end
```

**Comment by dheerajd-msys** [comment]
Hi @saadnaveed Could you please post your command that you are using which will help us reproduce and come up with solution?

Thanks!

**Comment by saadnaveed** [comment]
Hi @dheerajd-msys here's the exact command I'm running with some personal stuff commented out:

```
knife ec2 server create -N web008-c -I ami-0a00ce72 -Z us-west-2c -f c5.4xlarge --environment production --subnet <mysubnet> -g <mysecuritygroup> -r "myroles" -S <mysshkeyname> -i <pathtosshpemfile> --ebs-size 40 --ssh-user <myuser>
```

**Comment by breisig** [comment]
I am getting a similar issue to this.

**Comment by saadnaveed** [comment]
To provide a bit more background on this, it seems to be happening when an EC2 instance is created within a subnet that is private, which results in no public dns name or public IP address. 

Looking through the AWS SDK, it does seem like a `String` is returned for `private_dns_name`: https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/EC2/Types/Instance.html#private_dns_name-instance_method

**Comment by breisig** [comment]
@saadnaveed That's exactly what our situation is. We only build EC2 instances that are within a private subnet.

**Comment by dheerajd-msys** [comment]
Thanks @saadnaveed for clarification, we've got it reproduced and working on to fix it.

**Comment by breisig** [comment]
Any update?

**Comment by Park646** [comment]
The solution still doesn't fully resolve this issue. 

Using the Private DNS name causes workstations to not be able to connect if they are not running within the VPC. In our case Chef Workstation is on my local Mac in our office network and cannot resolve the Internal AWS Private DNS name and errors. 

I don't really understand what use case would require the ssh connection via DNS, we've always used the IP in the past. 

So commenting these two lines out resolved this issue for us. 

 def server_name
        return nil unless server

        if !server.public_dns_name.empty?
          server.public_dns_name
        #elsif !server.private_dns_name.empty?
         # server.private_dns_name
        else
          server.private_ip_address
        end
      end

**Comment by breisig** [comment]
I am having the EXACT same issue
