### ISSUE TITLE
Pushing 1.0.29 to Rubygems

### ISSUE THREAD

**Issue by breisig** [chef/knife-ec2#636]
# Version:
1.0.29

# Scenario:

It seems v1.0.28 is being installed when installing it as a gem. Can we get the latest 1.0.29 pushed to Ruby-gems as it's a pain that it automatically installs 1.0.28 and patching it.
# Steps to Reproduce:

gem install knife-ec2

# Expected Result:

Installs v1.0.29

# Actual Result:

Install v1.0.28

**Comment by dheerajd-msys** [comment]
Hi @breisig `knife-ec2 v1.0.31` is pushed to the Rubygems latest.
Please check.
